### ISSUE TITLE
Maximum number of items props

### ISSUE THREAD

**Issue by iCodePup** [renrizzolo/react-native-sectioned-multi-select#10]
Hello, 
Is it possible to define a maximum number of items that the user can pick from?

#feature

**Comment by renrizzolo** [comment]
I would do it like this.
But it's going to conflict if you use `selectChildren`. If the amount of children of a given parent is higher than your max items you won't be able to select that parent at all.

```
const maxItems = 5
...
  onSelectedItemsChange = (selectedItems) => {
    if ( selectedItems.length > maxItems ) {
      return;
    }
    this.setState({confirmText:`${selectedItems.length}/${maxItems}`})
    this.setState({ selectedItems })
  }
...
<SectionedMultiSelect
  confirmText={`Confirm - ${this.state.confirmText}`}
/>

```

**Comment by iCodePup** [comment]
Hello ,
Thanks, nice solution.
