### ISSUE TITLE
Need on onSearchTextChange function.

### ISSUE THREAD

**Issue by pk936** [renrizzolo/react-native-sectioned-multi-select#102]
Can you please provide a function onSearchTextChanged which will show what user has typed in search bar, so that developer can use that entered text and call api to get new values.

**Comment by pk936** [comment]
Ok got it.. it can be found using **filterItems** function prop. Thank you for this lovely package.

**Comment by RameshAmzur** [comment]
> Ok got it.. it can be found using **filterItems** function prop. Thank you for this lovely package.

Hi @pk936 
Do you have any idea with the below issue.
[](url)
https://github.com/renrizzolo/react-native-sectioned-multi-select/issues/165
