### ISSUE TITLE
Question: don’t show the (selected) headings as chips

### ISSUE THREAD

**Issue by oferRounds** [renrizzolo/react-native-sectioned-multi-select#103]
Hi,

First of all – thanks for this awesome library!

Second – quick question please:
I’m using the list with `selectChildren`= `true`. When user taps the a heading in order to select all its children, I would like only the children to be be shown as chips – without the heading.

Is this possible?

**Comment by renrizzolo** [comment]
Thanks!
Do you want the parent item chip to not be shown, or not be shown _and_ not be selected? 
There's no specific way to have the parent item not be selected – it would be quite complicated to do ( you wouldn't be able to unselect it for example).

Not displaying the chip is easy, but you'd have to render your own custom chips with `customChipRenderer` function prop.

something like: 
```js
customChipsRenderer = (props) => {

 // don't show parent item
 if (item[props.subKey] && item[props.subKey].length) return null

 // render a chip component for each selected item
  {props.selectedItems.map((singleSelectedItem) => {
   const item = this.SectionedMultiSelect._findItem(singleSelectedItem)
  return ( <Chip item={item} removeItem={this.SectionedMultiSelect._removeItem} /> )
 })}
}
```
you need a ref on the component for the above to work: 
```js
<SectionedMultiSelect
 ref={SectionedMultiSelect => (this.SectionedMultiSelect = SectionedMultiSelect)}
/>
```

**Comment by oferRounds** [comment]
Thanks! I want it to the job of selecting all sub-items – but don’t want it to be shown as a chip. Instead – if checked – shown only its sub-items.

I’ll try your solution!

**Comment by oferRounds** [comment]
I don’t see the there is such <Chip> component available, am I missing something?

**Comment by oferRounds** [comment]
Also, would this solution work well with tapping a chip to remove it / remove all?

**Comment by oferRounds** [comment]
For example, tapping a sub-item should remove the heading as well (both for the chip and from the actual data)

**Comment by renrizzolo** [comment]
@oferRounds no, there is no chip component exported, you'd have to create it yourself. 

> Also, would this solution work well with tapping a chip to remove it / remove all?

Yes, you could remove individual items with `this.SectionedMultiSelect._removeItem(item)`, and add a remove all button with `this.SectionedMultiSelect._removeAllItems()`.

> For example, tapping a sub-item should remove the heading as well (both for the chip and from the actual data)

Not really sure I follow.
Given parent:`fruits`, children: `apple`, `orange`, `banana`
You want to tap `fruits`, and show only `apple`, `orange` and `banana` chips (fruits is also selected but not shown as a chip) (the above code does this, if you use `selectChildren` prop)

Then tap remove on the `banana` chip, showing only `apple` and `orange`, and removing `fruits` from selected items ( and `banana`)?

This doesn't sound like good UX, so sorry if I'm misunderstanding.

**Comment by oferRounds** [comment]
@renrizzolo sorry for the delay on my side!
What I mean is this:

- **Inside the picker**, the idea is that the heading will be used as a helper-button to select all/none. In that sense, If the user tapped it to select all `fruits`, and then tapped the `banana` to deselect it, the `fruits` heading should now automatically get de-selected as well (as it no longer reflects the current state, as one of the fruits is not selected). 

     Following the same logic, If he now re-tapped the `banana` – causing all the fruits to get selected – then the `fruits` heading show also get automatically selected

- **Outside the picker**, showing the heading as a chip is not relevant, as it does not really reflects an item – as said, it is only a helper-button (and following the previous logic, if all fruits were selected, and now the use remove the `orange` chip, now when he re-open the picker, the `fruits` heading should present itself as not-selected)

Makes sense? Sorry for the long text...

**Comment by renrizzolo** [comment]
I understand what you mean now. It's kind of the opposite functionality of `highlightChildren`.

Are you concerned about the parent item ids being added to the `selectedItems` or not?
The expected behaviour is for a selected item id to be put in the `selectedItems` array.

There's a couple of ways to handle it:

- add a prop to hide parent items from chips
- add a prop that would remove the parent of any subItem when deselected ( to be used in conjunction with `selectChildren`
Note this isn't going to select the parent if all sub items and selected individually.

OR

- add a prop that makes `selectChildren` not select the parent (the parent would never be selected)

**Comment by oferRounds** [comment]
Thank you, I’ll look into your suggestions!
