### ISSUE TITLE
Suggestion/Question: show selected items check mark left to the text

### ISSUE THREAD

**Issue by oferRounds** [renrizzolo/react-native-sectioned-multi-select#104]
I think showing the checkmark left to text makes everything less clutter and more clear. I think this also what is more popular amongst such mobile components. 

Would you consider changing this behaviour? It’s also possible to add it as an option if you prefer

![image](https://user-images.githubusercontent.com/1477963/56218124-12863d80-606d-11e9-8ceb-b517d4fb9045.png)

**Comment by renrizzolo** [comment]
I'll look into making this an option!

**Comment by oferRounds** [comment]
Thank you!
