### ISSUE TITLE
Question: add major-heading which select all

### ISSUE THREAD

**Issue by oferRounds** [renrizzolo/react-native-sectioned-multi-select#105]
Hi, is there a `selectAll` option? I’d the first row would be show a 'Select all' text, and tapping it will select all items in the list. Is this possible?

**Comment by oferRounds** [comment]
Actually more like a toggle button of select/deselect all

**Comment by renrizzolo** [comment]
Hi @oferRounds, 
I can add a `_selectAllItems` method to the class. Then you could use it in the `headerComponent`.
something like:
```js
  SelectOrRemoveAll = () => (
    <TouchableOpacity
      onPress={this.state.selectedItems.length ? this.SectionedMultiSelect._removeAllItems : this.SectionedMultiSelect._selectAllItems}
    >
      <Text>{this.state.selectedItems.length ? 'Remove' : 'Select'} all</Text>
    </TouchableOpacity>
  )
```
Note this uses a ref to access the class methods. `    <SectionedMultiSelect  ref={SectionedMultiSelect => (this.SectionedMultiSelect = SectionedMultiSelect)} />`

**Comment by oferRounds** [comment]
Sounds great, would love that! Thank you!
