### ISSUE TITLE
Question: how to render chips to another component

### ISSUE THREAD

**Issue by Ethereal0** [renrizzolo/react-native-sectioned-multi-select#106]
Hello, before of all, you did a great job for creating this multi select picker.

I need small help. Let's say that i have created another view which is container for chips and i want to show selected items in that container. How is possible to do that? Please also write me some small example. Thanks!

**Comment by renrizzolo** [comment]
It's currently not possible. I am working on an update which would allow this through the Context API (potentially).

**Comment by vrinch** [comment]
It is possible by looking at the example. Using thing renderSelectedText function
And calling it in another class component
