### ISSUE TITLE
Select multiple children of only one parent

### ISSUE THREAD

**Issue by Abhijeetjaiswalit** [renrizzolo/react-native-sectioned-multi-select#109]
Is there any way where i have to allow the users to select multiple childs of only one parent. i.e if an user selects 2 children of first parent, then by selecting any other parent's child(multiple or even a single) will result in deselection of previously selected parent's children.
@renrizzolo

**Comment by yongsokheng** [comment]
I meet this issue too

**Comment by anonymousdeveloper96** [comment]
I met with the issue as well

**Comment by NativLouie** [comment]
@Abhijeetjaiswalit did you figure something out ? thanks
