### ISSUE TITLE
Section selected when children was selected

### ISSUE THREAD

**Issue by iCodePup** [renrizzolo/react-native-sectioned-multi-select#11]
Hello,
I have a weird issue.
When i select one specific children in the list , an other section parent was selected...
Anyway, why a parent section can be selected ?

I will try to investigate more.

Thanks.

**Comment by renrizzolo** [comment]
hey, I'm pretty sure this can only happen if they have the same ID, is that the case?

**Comment by iCodePup** [comment]
Hello,

Sorry, you right
