### ISSUE TITLE
Custom RowItem & RowSubItem Components

### ISSUE THREAD

**Issue by zlanich** [renrizzolo/react-native-sectioned-multi-select#112]
Hey there! I'd like to use your multi-select, but one immediate limitation I'm seeing is no ability to provide a custom component for the RowItem or RowSubItem (especially). If we were to create something like a Country Picker using this, we'd need to show the country flag (for example), but it looks like it currently only supports Text. 

Would you be willing to add 2 methods for these, and pass relevant props into them?

**Comment by renrizzolo** [comment]
Yes, that can be added.
You can use the `iconKey` prop if you have icons in your items.

**Comment by zlanich** [comment]
@renrizzolo Yea, I did see the iconKey. That would work for a country picker. It was probably a bad example. lol. I'm also thinking of other needs beyond Text.

**Comment by FadiAboMsalam** [comment]
@renrizzolo  in my case i need to show list of subservices  and their price 
for example 
service1 -  price$
but i can only render one text and can't seem to have the ability to put the service on the start of row and price at end of row to achieve something like (justifyContent:"space-between")
any help is appreciated

**Comment by BalonBabylon** [comment]
Also encountered this problem,
Opened a PR at https://github.com/renrizzolo/react-native-sectioned-multi-select/pull/117

added a 'customSubItemContentRenderer' prop that lets the developer keep the item selection logic while also replacing the RowSubItem content with your own one.

**Comment by rafaelgilead** [comment]
iconKey not working for me.
I try the 3 ways.
