### ISSUE TITLE
SafeAreaView not Working

### ISSUE THREAD

**Issue by zlanich** [renrizzolo/react-native-sectioned-multi-select#113]
Hey there! It looks like the SafeAreaView is not working for some reason. It's working fine elsewhere in my app.

Screenshots:
- Showing not working: http://zsl.io/kyqPyF
- Showing that the SafeAreaView is in fact there: http://zsl.io/xTjDA6

**Comment by renrizzolo** [comment]
looks like I broke it in ab8e2711f728f482285158b6f86e881c2c3bcfcb

**Comment by zlanich** [comment]
@renrizzolo Gotcha. I'll see if I can patch it for now, but thanks for marking this as a bug, and for the fast responses!
