### ISSUE TITLE
Adding values to each child

### ISSUE THREAD

**Issue by vrinch** [renrizzolo/react-native-sectioned-multi-select#116]
Hi, 

Thanks for this package. I’m roughly new to react native and I am currently working on a project using this package. I’d like to know if it’s possible to add values to each child array and add them up when more than one child is selected?

**Comment by renrizzolo** [comment]
Sorry I don't know what you mean, please give me an example.

**Comment by vrinch** [comment]
you already have unique IDs assigned to each child element. Is it possible to add another array option called value.
For instance, I have listed different car spare parts which all have different unique IDs. Now when a customer is buying, I want to be able to assign values to each of these spare parts (some might be the same value, not unique) because I want to be able to compute the total value of all the car spare parts selected.
Does that make sense?

**Comment by renrizzolo** [comment]
Well, you can do whatever you like with your data!
The library isn't designed to do any data handling.

This is what I'd do - not sure if it works for your case.
It should add to state the accumulated value of the selected items per set of children with the keys being the parent item name.

```js
const items = [
 { 
  name: 'parts list 1',
  id: 0, 
  children: [
   {
    name: 'part 1', id: 1, value: 236.50, childOf: 'parts list 1'
   },
   {
    name: 'part 2', id: 2, value: 125.00, childOf: 'parts list 1'
   },
 ]
},
 { 
  name: 'parts list 2',
  id: 3, 
  children: [
   {
    name: 'part 3', id: 4, value: 37.20, childOf: 'parts list 2'
   },
   {
    name: 'part 4', id: 5, value: 12.00, childOf: 'parts list 2'
   },
 ]
},
]
addValues = (items) => {
const temp = {'parts list 1': 0, 'parts list 2': 0}
 items.forEach((val) => {
  if (val.value){
   temp[val.childOf] = temp[val.childOf] + val.value;
   this.setState({
      this.state[val.childOf]: temp[val.childOf]
    })
  }
 })
}
<SectionedMultiSelect 
  items={items}         
  selectedItems={this.state.selectedItems}
  onSelectedItemsChange={(selectedItems ) =>  this.setState({ selectedItems })}
  onSelectedItemObjectsChange={this.addValues}
 />
```

If you just want to add the total values (not separate them), a simple reduce will do it. 
`(items.reduce((acc, curr) => curr.value ? acc + curr.value : acc, 0)`

**Comment by vrinch** [comment]
Yes, I just want to add the total value and not separate them.
However, I dont know where to add the simple reduce code
       items.reduce((acc, curr) => curr.value ? acc + curr.value : acc, 0);
and also, I would be very grateful if you can run the code on your end to see if it works.
thanks

**Comment by renrizzolo** [comment]
The result of the reduce function is your sum.
You use the `onSelectedItemObjectsChange` prop to receive the objects of the selected items.

```js
addValues = (items) => {
const sum = items.reduce((acc, curr) => curr.value ? acc + curr.value : acc, 0);
  this.setState({
   total: sum
})
...
onSelectedItemObjectsChange={this.addValues}
```

**Comment by vrinch** [comment]
it keeps throwing this error
![image](https://user-images.githubusercontent.com/51086859/59440489-5c826a00-8df7-11e9-94d1-c5a6cdc9e308.png)

when I take the item out from the bracket, I get this

![image](https://user-images.githubusercontent.com/51086859/59440554-791ea200-8df7-11e9-867a-6b29a929c1d0.png)

if you dont mind, i could add you to a private repo so you could see how my code is and in what situation I want to use it

thanks

**Comment by vrinch** [comment]
Below is a sample code of where I want to do the sum 
I would be really glad if you can help me with this, as I have been stuck on this for about a week.
```

import React, { Component } from 'react';
import { View, StyleSheet, Text, TouchableHighlight, TouchableOpacity,
Modal, Image, KeyboardAvoidingView, Keyboard } from 'react-native';
import SectionedMultiSelect from 'react-native-sectioned-multi-select';

const items = [
 { 
  name: 'parts list 1',
  id: 0, 
  children: [
   {
    name: 'part 1', id: 1, value: 236.50, childOf: 'parts list 1'
   },
   {
    name: 'part 2', id: 2, value: 125.00, childOf: 'parts list 1'
   },
 ]
},
 { 
  name: 'parts list 2',
  id: 3, 
  children: [
   {
    name: 'part 3', id: 4, value: 37.20, childOf: 'parts list 2'
   },
   {
    name: 'part 4', id: 5, value: 12.00, childOf: 'parts list 2'
   },
 ]
},
]
class Details extends Component {
  constructor(props) {
    super(props);
    // Initialize State
    this.state = {
      items: 0,
      selectedItems: [],
      selectedItemObjects: [],
      displayKey: 'name',
      value: '',
    };
      }

  onCancel = () => {
    this.setState({
      selectedItems: [],
    });
  }

onSelectedItemsChange = (selectedItems) => {
  this.setState({
    selectedItems
  });
  this.props.handleSelectedItems(selectedItems);
};

onSelectedItemObjectsChange = (selectedItemObjects) => {
  this.setState({ selectedItemObjects });
  console.log(selectedItemObjects);
  this.props.handleSelectedItemObjects(selectedItemObjects);
}

  render() {
<View>
          <SectionedMultiSelect
                    items={ParcelCategories}
                    uniqueKey="id"
                    subKey="children"
                    displayKey={this.state.displayKey}
                    selectText="Select parcel(s) category..."
                    showDropDowns
                    readOnlyHeadings
                    animateDropDowns
                    showCancelButton
                    onCancel={this.onCancel}
                    onConfirm={(e) => console.log(e)}
                    onSelectedItemsChange={this.onSelectedItemsChange}
                    onSelectedItemObjectsChange={this.onSelectedItemObjectsChange}
                    selectedItems={this.state.selectedItems}
                    itemNumberOfLines={3}
                    selectLabelNumberOfLines={3}
          />
    <View>
              <Text>(where I want to display the total sum)</Text>
   </View>
</View>
}

export default Details;

```
