### ISSUE TITLE
is it necessary that item array should be same as defined ?

### ISSUE THREAD

**Issue by ismailkhan89** [renrizzolo/react-native-sectioned-multi-select#118]
I have array like 
const items = [
  {

Skill: "Test"
SkillID: "1"
}
]
instead of like this 
const items = [
  {
    name: 'Fruits',
    id: 0,
}
]

it's not working so what should i do for that ? is there's any option for this kind of array ?

**Comment by renrizzolo** [comment]
Use `uniqueKey` and `displayKey` props:
https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/master/README.md#items
