### ISSUE TITLE
Keep modal open until confirmed in single selection mode

### ISSUE THREAD

**Issue by skizzo** [renrizzolo/react-native-sectioned-multi-select#119]
Hi,
first of all, thanks for this great component!

I noticed that when I add the `single={true}` property to my `SectionedMultiSelect`, the whole view automatically closes as soon as I change my selection once, independent of whether I have a confirm button or not. Is it possible to prevent this somehow?

I know the workaround would be to set `single={false}` and then on each selection change just compare the selected items with the last ones in my custom `onSelectedItemsChange` function and compute a new Array with just one single item selected, but this feels a bit hacky.

Thanks!

**Comment by renrizzolo** [comment]
I'd say do that for now... 
Could be addded as a prop although I'm trying to limit new props as there are nearly 70 in this lib.

**Comment by empiteranga** [comment]
is there new prop to do that

**Comment by UtilExe** [comment]
@renrizzolo Any news on this prop? Thanks!

**Comment by renrizzolo** [comment]
I think we can just add `closeOnSingleSelect` prop and check for it here https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/master/lib/sectioned-multi-select.js#L616

**Comment by henryteng07** [comment]
Heres the patch-package file in case anyone wants to add closeOnSingleSelect prop 
[Uploading react-native-sectioned-multi-select+0.10.0.patch…]()
