### ISSUE TITLE
Need more customize of "xxx selected"

### ISSUE THREAD

**Issue by xmannv** [renrizzolo/react-native-sectioned-multi-select#12]
Need add a customize of the text string "selected" in "(xxx selected)"

**Comment by Xyzor** [comment]
+1

**Comment by renrizzolo** [comment]
Thanks - #13

**Comment by dmitriyermolin** [comment]
First, thanks for this customization. But I need even more customization of `selectedText` prop. In Russian (and in some other languages, I suppose) 'selected' usually translated as past passive participle and it has suffixes depending on preceding number and gender (yes, we have genders for nouns). So '1 selected' and '2 selected' would have different endings.
Changing `selectedText` prop type from `PropTypes.string` to `PropTypes.oneOfType([ PropTypes.string, PropTypes.func ])` would be more than sufficient. In that case, I could use a function returning string to solve the issue.

**Comment by renrizzolo** [comment]
Fixed (function allowed) in `0.4.0`
