### ISSUE TITLE
Redundant Object.assigne({},item) inside _filterItems function

### ISSUE THREAD

**Issue by bartoszgolebiowski** [renrizzolo/react-native-sectioned-multi-select#120]
Hey
Thank you for the fantastic lib, I'm loving it!
Anyway, I was trying to optimize your component <SectionedMultiSelect> and I have found something interesting.

385 line is coping the whole 'item' object, and line after there is cleaning one of the fields.
I highly recommend copying only two fields 'id' and 'name' Object.assign({}, { 'id': item.id, 'name': item.name })

also 
389 line is also coping the whole array, IMO you can use simple push function.
newItem[subKey].push(sub)

This is local variable so IMO there is no need to sustain immutability. 
The reason why I was analyzing your code is 100000 element list inside 'items' property, which freezes my simulation.  

BR
Bartosz

**Comment by renrizzolo** [comment]
Thanks, appreciate your help!
I'll take a look.
