### ISSUE TITLE
How to change 'check' icon's color?

### ISSUE THREAD

**Issue by haolipang** [renrizzolo/react-native-sectioned-multi-select#122]
Hi is there any way to change the color of symbol '✓'?

**Comment by SergeyIsakhanyan** [comment]
Hi @haolipang. You can change color of that icon by passing your own Icon component: 
`selectedIconComponent={<Icon size={14} name="check" style={{ color: '#fff', marginRight: 10 }} />}`

You must import `<Icon />` from react-native-vector-icons

**Comment by renrizzolo** [comment]
it's also changeable with `colors.success`.

```js
 <SectionedMultiSelect colors={{success: 'purple'}} />
```
