### ISSUE TITLE
How to pass emoji icon

### ISSUE THREAD

**Issue by buchidiai** [renrizzolo/react-native-sectioned-multi-select#128]
Is it possible to pass an emoji icon as shown in the example ? I tried but it crashed. thanks in advance.
![Screen Shot 2019-08-05 at 4 55 01 PM](https://user-images.githubusercontent.com/31743169/62497608-14057e00-b7a2-11e9-9b09-785433d54304.png)

**Comment by renrizzolo** [comment]
The icon can either be an image file reference, a uri or an `<Icon/>` – it doesn't return text.

So in order to return an emoji, you would have to create your own `iconRenderer` function.

```jsx
import Icon from 'react-native-vector-icons/MaterialIcons'
...
iconRenderer = (props) => {
    let iconComponent
    // the default icons
    const Icn = (
      <Icon {...props} />
    )
    const Emoji = (
      // style this how you like
      <View style={{marginRight: 8}}>
        <Text>{props.name}</Text>
      </View>
    )
    switch (props.name) {
      case 'search':
        iconComponent = Icn
        break
      case 'keyboard-arrow-up':
        iconComponent = Icn
        break
      case 'keyboard-arrow-down':
        iconComponent = Icn
        break
      case 'close':
        iconComponent = Icn
        break
      case 'check':
        iconComponent = Icn
        break
      case 'cancel':
        iconComponent = Icn
        break
      case '🇦🇽': // you can just have emoji as the default rather than make a case for each separate flag.
                 // But you will have to update this function if any new icons were to be added to the lib.
          iconComponent = Emoji
        break
      default:
        iconComponent = Emoji
        break
    }
    return <View>{iconComponent}</View>
  }
...
  <SectionedMultiSelect ... iconRenderer={this.iconRenderer} />
```

I might export an array of default icons in the future to make this easier.
so you could do `return iconSet.includes(name) ? Icn : Emoji`

**Comment by buchidiai** [comment]
@renrizzolo sorry for the late response.  my use-case would be to let a user select from over 300 countries  which is in a JSON format. How would i render as emoji and name ? thanks once again.
![Screen Shot 2019-08-08 at 1 15 21 PM](https://user-images.githubusercontent.com/31743169/62727292-c75ab680-b9de-11e9-9e1c-57b0a16620dd.png)

**Comment by buchidiai** [comment]
nvm i figured it out thanks anyways.

**Comment by renrizzolo** [comment]
> nvm i figured it out thanks anyways.

What method did you end up using?

**Comment by buchidiai** [comment]
i mapped the flag and name to a key/value for display purposes with some space

```
let countries = cities.map((item, index) => {
	if (item) {
		return {
			id: index + 1,
			name: ` ${ item.flag }   ${ item.name }`,
		}
	}
})

```
