### ISSUE TITLE
How to disallow parent selection if there are children

### ISSUE THREAD

**Issue by bohan0** [renrizzolo/react-native-sectioned-multi-select#130]
Say I have the following:

----
Supermarket {children: [Aldi, Costco, Wallmart]}
Security
Labourer
Health {children: [Doctor, Nurse]}
----

How do I allow Security and Labourer (parents with no children) to be selected while disallowing Supermarket and Health (parents with children) to be selected? Basically I want to force selection of Doctor or Nurse under Health instead of the Health itself.

**Comment by renrizzolo** [comment]
There's no way to do this globally but you can manually add disabled to any item object. 
i.e add `disabled: true` to Supermarket and Health parent items.
