### ISSUE TITLE
Getting Border after every 2 items

### ISSUE THREAD

**Issue by pateljaykesh** [renrizzolo/react-native-sectioned-multi-select#132]
![Screenshot_20190818](https://user-images.githubusercontent.com/2973241/63223166-19fe5480-c1cf-11e9-9c4c-aa35d3df9e7d.jpg)

See above screenshot. I am not using sub item. I would like to remove border. Can you help on this?

**Comment by renrizzolo** [comment]
I'm not sure why it's showing every second item, but the item separator is styled by `styles.separator`, so if you add `styles={{separator: {height:0} }}` it should remove it.
