### ISSUE TITLE
How can I use a custom search Icon? searchIconComponent

### ISSUE THREAD

**Issue by drinikol** [renrizzolo/react-native-sectioned-multi-select#133]
`searchIconComponent`
Is there a way to use a custom icon using require? I need a white icon rather than the black magnifying glass

**Comment by renrizzolo** [comment]
it should probably have a color prop that maps to the colors object.
You can do `searchIconComponent={() => <Icon name="search" color="white" size={18} />}`, no?
or `searchIconComponent={() => <Image src={require('icon.png')} />}` ?
