### ISSUE TITLE
Need to change Text Color of Chip

### ISSUE THREAD

**Issue by gopikasireddy202** [renrizzolo/react-native-sectioned-multi-select#135]
Hi,
I need to change (To - text color to red and Font Size of chip.How to change it.For your reference i attached screenshot also.
![Simulator Screen Shot - iPhone X - 2019-08-28 at 20 29 16](https://user-images.githubusercontent.com/43564071/64145304-d5f98980-ce35-11e9-8655-506265a88b38.png)

**Comment by raphaelluiz128** [comment]
i whaiting for this

**Comment by renrizzolo** [comment]
To change the style of the select text use a `renderSelectText` function.

```JS
 renderSelectText = () => {
    const { selectedItemObjects } = this.state

    const selectText = selectedItemObjects.length
      ? `To ${selectedItemObjects
        .map((item, i) => {
          let label = `${item.title}, `
          if (i === selectedItemObjects.length - 2) label = `${item.title} and `
          if (i === selectedItemObjects.length - 1) label = `${item.title}.`
          return label
        })
        .join('')}`
      : 'To'
      return <Text style={{ color: 'red', fontSize: 24 }}>{selectText}</Text>
  }
```

To change the chip color you can use the `chipColor` color (text, border and X icon) or use the `chipText` style to only style the text.
