### ISSUE TITLE
componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

### ISSUE THREAD

**Issue by dev3288** [renrizzolo/react-native-sectioned-multi-select#136]
I am getting this warning

Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: SectionedMultiSelect

    "react": "^16.8.6",
    "react-native": "^0.60.5",
    "react-native-sectioned-multi-select": "^0.7.1",

**Comment by fri0z** [comment]
@renrizzolo please update components
