### ISSUE TITLE
How can I apply height on this screen?

### ISSUE THREAD

**Issue by Rharuow** [renrizzolo/react-native-sectioned-multi-select#137]
How can I apply height on this container?
![image](https://user-images.githubusercontent.com/19626398/64806019-b31f5180-d568-11e9-9b7f-f57bdc07301a.png)

**Comment by renrizzolo** [comment]
You might want to apply the safe area view prop, and have a look at the possible styles in the readme.

**Comment by juliobrim** [comment]
I have the same problam, and solve using this on styles:
`<SectionedMultiSelect 
  styles={{                       
    container: {
      flex: 0,
      height: '70%',
      width: '80%',
      alignSelf: 'center',      
    },
    modalWrapper: {
      alignItems: 'center',
      justifyContent: 'center',
    },
  }}`

My first mistake was using 'style' instead of 'styles'.
