### ISSUE TITLE
Example uses this.maxItems and this.state.maxItems but this.state.maxItems is not declaired

### ISSUE THREAD

**Issue by gomac** [renrizzolo/react-native-sectioned-multi-select#138]
Hi,
The subject line says it all. setState is called to update "maxItems" but I don't see it declared.

I've only been using RN for about a year. Am I missing something or is it just an oversight?

Gordon

**Comment by renrizzolo** [comment]
I guess it's an oversight to not declare an initial value. But you can still set state on an as yet undefined key.
This.maxItems is a constant values, and this.state.maxItems is used to track the number of items.
