### ISSUE TITLE
Prop for custome display value

### ISSUE THREAD

**Issue by Xyzor** [renrizzolo/react-native-sectioned-multi-select#14]
Is it possible to define which attribute is shown in the list.
>Eg: A `displayAttribute='title'` prop

If not, do you accept a PR for this?

**Comment by renrizzolo** [comment]
@Xyzor not sure I follow what this is for?

**Comment by Xyzor** [comment]
I'd like to be able to provide a data object like this to the multiselect:
`[
  {  
    title: "Fruits",
    id: 0,
    children: [{
        title: "Apple",
        id: 10,
      }
    ]
  }
]`

**Comment by renrizzolo** [comment]
gotcha. 
`titleKey` prop will be added in the next version. ( you can try it on dev branch),

**Comment by renrizzolo** [comment]
Added and changed to `displayKey`.
