### ISSUE TITLE
Single selection display nothing

### ISSUE THREAD

**Issue by Cchumi** [renrizzolo/react-native-sectioned-multi-select#143]
Hi I try to use the single option 

single={true}

but when I select an item it show nothing as expected.
If I put single={false} it works but that not the behavior I want.

How to achieve a single item selection and show it ?

Thanks

**Comment by renrizzolo** [comment]
Single doesn't show a chip. Single is designed to behave like a select. The text of the single item will be put as the select label (or however you customize the label).

**Comment by KBiswas98** [comment]
==> readOnlyHeadings={true}
|| to
==> readOnlyHeadings={false}


const items = [
  // this is the parent or 'item'
   
      {
        name: 'Apple',
        id: 10,
      },
      {
        name: 'Strawberry',
        id: 17,
      },
      {
        name: 'Pineapple',
        id: 13,
      },
      {
        name: 'Banana',
        id: 14,
      },
      {
        name: 'Watermelon',
        id: 15,
      },
      {
        name: 'Kiwi fruit',
        id: 16,
      },
      {
        name: 'Apple',
        id: 20,
      },
      {
        name: 'Strawberry',
        id: 27,
      },
      {
        name: 'Pineapple',
        id: 23,
      },
      {
        name: 'Banana',
        id: 24,
      },
      {
        name: 'Watermelon',
        id: 25,
      },
      {
        name: 'Kiwi fruit',
        id: 26,
      },
];

<SectionedMultiSelect
                items={items}
                uniqueKey="id"
                subKey="children"
                selectText="Choose some things..."
                showDropDowns={true}
                readOnlyHeadings={false}
                onSelectedItemsChange={this.onSelectedItemsChange}
                selectedItems={this.state.selectedItems}
                />
