### ISSUE TITLE
Getting parent item with selected child item

### ISSUE THREAD

**Issue by harish-bisht** [renrizzolo/react-native-sectioned-multi-select#144]
How parent item can be get with selected child item?

**Comment by renrizzolo** [comment]
Something like this.
```JS
findParent = (itemId) => {
    const { items } = this.state
    let match = false
    items.forEach((item) => {
      item.children &&
        item.children.filter(({ id }) => {
          if (id === itemId) {
            match = item.id
          }
        })
    })
    return match
  }
```

**Comment by vinhtranSmartDev** [comment]
Hi @renrizzolo , Shall we make a  function to return selected parent?

**Comment by hieunguyendut** [comment]
Hi @renrizzolo , Shall we make a  function to return selected parent?

**Comment by renrizzolo** [comment]
How would you expect to use that? As in just a method via the ref?

**Comment by cdiaz** [comment]
> How would you expect to use that? As in just a method via the ref?

Hi @renrizzolo , I would like to expect the **onSelectedItemObjectsChange** method to return an object that contains both the parent and child.

```
 [
   {
    "id": 2,
    "name": "parent",
    "children": {
      "id": 4,
      "name": "children"
    }
  }
]
```
