### ISSUE TITLE
Wrong height of the dropdown list

### ISSUE THREAD

**Issue by x1062316223** [renrizzolo/react-native-sectioned-multi-select#145]
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-02 at 20 08 27](https://user-images.githubusercontent.com/43434214/66036422-84394180-e550-11e9-990b-e26808179954.png)
the height of the opened menu seems cover the iphone X status bar, is this possible to make the max height smaller with styles?

**Comment by chiennv97** [comment]
add style to fix this
`styles={{
             container: {
                        marginTop: 30
                      }
                  }}`
