### ISSUE TITLE
Can't able to get top search result for the words with space which are matched.

### ISSUE THREAD

**Issue by ChandreshRana** [renrizzolo/react-native-sectioned-multi-select#146]
![Search](https://user-images.githubusercontent.com/10288757/66197322-c7fa8b00-e6b7-11e9-9687-7afb339d0c2b.png)

Here in above screenshot. The word "San Francisco" which i was trying to search, But it was not come to first in search list.

**Comment by renrizzolo** [comment]
The filter could use some love.
