### ISSUE TITLE
Question: option to present only the popup?

### ISSUE THREAD

**Issue by oferRounds** [renrizzolo/react-native-sectioned-multi-select#149]
Hi! thanks for this great library again!

Question please: i’d like to trigger the open of the popup from my own custom button, while tapping the button will open only the popup - with out the chips and selectText button

Is there such an option?

Thank you again!
Ofer

**Comment by renrizzolo** [comment]
Add a ref to the component `ref={SectionedMultiSelect => (this.SectionedMultiSelect = SectionedMultiSelect)}`
Then you can use the internal method `this.SectionedMultiSelect._toggleSelector()` to open / close the modal

You can use the props `hideSelect={true}`and `showChips={false}` to hide the selector and chips

**Comment by oferRounds** [comment]
It works! Thank you very much!!!

**Comment by sam9010** [comment]
@oferRounds  can i see your code?
because i want my list in modal, not in bottom of list
