### ISSUE TITLE
How to add a cancel button for sectioned-multi-select?

### ISSUE THREAD

**Issue by harikrishnanp** [renrizzolo/react-native-sectioned-multi-select#15]
The sectioned-multi-select works perfectly for me. How can I add a cancel button for this? Now there is only "Confirm" button. Please advice.

**Comment by renrizzolo** [comment]
Hi, there's currently not a cancel button.
Would you want it to remove ALL currently selected items?

**Comment by harikrishnanp** [comment]
I have seen `showRemoveAll` prop to remove all items. But I have to achieve that via cancel button in the UI. Please advice.

**Comment by harikrishnanp** [comment]
I have seen the code. I think Cancel button should remove only newly selected items instead removing all items. Could you please implement that or guide me? I need that urgently.

**Comment by renrizzolo** [comment]
@harikrishnanp we can't do this with the current implementation.

I added `onCancel` and `onConfirm` handlers so you can do it yourself by saving the items to another state after every confirm, then reverting your selected items to that state after cancel.

This won't properly highlight children if you're using that. 
It also won't care if you removed items by pressing the chips or by toggling the items in the modal. So in that sense it works more like an undo button.

```
  onSelectedItemsChange = (selectedItems) => {
    this.setState({ selectedItems })
  }

  onConfirm = () => {
    this.setState({ currentItems: this.state.selectedItems })
  }
  onCancel = () => {
    this.SectionedMultiSelect._removeAllItems();
    this.setState({ 
      selectedItems: this.state.currentItems
    })
  }

 <SectionedMultiSelect
  onCancel={this.onCancel}
  onConfirm={this.onConfirm}
  ...
 />
```

**Comment by harikrishnanp** [comment]
Thank you. I'm not using children. So that won't be a problem. Let me try.

**Comment by renrizzolo** [comment]
Let me know if there are still any problems with this.
