### ISSUE TITLE
Is that any way to disable chips close button

### ISSUE THREAD

**Issue by peterlau0010** [renrizzolo/react-native-sectioned-multi-select#150]
Is that any way to disable the chips remove the selected item?

Since the user in confirmation page, should not be able to edit the form again.

![image](https://user-images.githubusercontent.com/9346306/68002396-a1724480-fca3-11e9-998e-f3ee003b82bc.png)

**Comment by renrizzolo** [comment]
update the package and use `hideChipRemove` to hide the chip remove button.
