### ISSUE TITLE
Warning message 

### ISSUE THREAD

**Issue by mica83** [renrizzolo/react-native-sectioned-multi-select#151]
I have this warning message in ios simulator:

**VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.**

This is my render function:

return (
        <SafeAreaView forceInset={{ top: 'always' }} style={globalStyles.debug} >
            <View>
                <SectionedMultiSelect
                    items={items}
                    uniqueKey="id"
                    selectText="Seleziona la Lingua"
                    onSelectedItemsChange={(newLanguages) => setActivity({ ...activity, languages: newLanguages })}
                    selectedItems={activity.languages}
                />
            </View>
        </SafeAreaView>
    );

"dependencies": {
    "@react-native-community/async-storage": "^1.6.2",
    "@react-native-community/google-signin": "^3.0.3",
    "@react-native-firebase/app": "^6.0.3",
    "@react-native-firebase/auth": "^6.0.3",
    "axios": "^0.19.0",
    "axios-debug-log": "^0.6.2",
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-image-picker": "^1.1.0",
    "react-native-reanimated": "^1.4.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-native-sectioned-multi-select": "^0.7.2",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.5.6"
  },

**Comment by renrizzolo** [comment]
Should be fixed as of `v0.7.3`
