### ISSUE TITLE
New API?

### ISSUE THREAD

**Issue by hgezim** [renrizzolo/react-native-sectioned-multi-select#155]
I really love this library. It's exactly what I needed and saved me a lot of time. Wish I knew about it and had access to it for general react as well.

However, the API leaves a lot to [be desired](https://github.com/renrizzolo/react-native-sectioned-multi-select/issues/60#issuecomment-560256385).

For extensibility, [Downshift](https://www.npmjs.com/package/downshift) seemed like a good example we could follow. Would love to know your thoughts.

**Comment by renrizzolo** [comment]
Totally agree with you!
I was actually working on an update inspired by Downshift, that used the Context API and render functions to be able to arrange all the components how you like / render them in different places.
But it's just too convoluted to merge into the current options/styling system, and would be better to be rewritten from scratch imo.

![Screen Shot 2019-12-06 at 11 14 25 am](https://user-images.githubusercontent.com/13904763/70284964-03314b80-181a-11ea-8d6e-8dfd5081139b.png)
