### ISSUE TITLE
RTL support?

### ISSUE THREAD

**Issue by sommeshEwall** [renrizzolo/react-native-sectioned-multi-select#157]
Thanks for this wonderful library.
I have been using this library for a long time.
I'm facing an issue like when I select an Arabic word from the dropdown list, it's not showing in the `selectedItems` area. Instead, it's displaying a blank area.  Please let me know is there any other way to display Arabic names when selected?

**Comment by renrizzolo** [comment]
Can you give me a reproduction? I just tried some arabic items and they show up fine both in the list and on the chips.

**Comment by sommeshEwall** [comment]
"npm": ^6.9.0,
"react-native": ^0.59.2
"react-native-sectioned-multi-select": ^0.7.6

This is the code 

```
import React from 'react';
import SectionedMultiSelect from 'react-native-sectioned-multi-select';
import { View } from 'react-native';

const items = [
  {
    name: 'العاشر ليونيكود',
    id: 1,
  },
  {
    name: 'العالمية انترنيت ويونيكود،',
    id: 2,
  },
  {
    name: 'Pineapple',
    id: 3,
  },
  {
    name: 'Banana',
    id: 4,
  },
];
class Add extends React.Component {
  constructor() {
    super();
    this.state = {
      selectedItems: [],
    };
  }
  onSelectedItemsChange = selectedItems => {
    this.setState({ selectedItems });
  };
  render() {
    return (
      <View>
        <SectionedMultiSelect
          items={items}
          uniqueKey="id"
          selectText="Please select an value"
          searchPlaceholderText="Search"
          showDropDowns={true}
          single={true}
          readOnlyHeadings={false}
          onSelectedItemsChange={this.onSelectedItemsChange}
          selectedItems={this.state.selectedItems}
        />
      </View>
    );
  }
}

export default Add;

```

![dropdown](https://user-images.githubusercontent.com/32094388/74903594-6705f200-53cf-11ea-8cd4-32923080c5c8.gif)


@renrizzolo Kindly let me know why is the Arabic text not getting displayed when selected?
Is there anything I'm doing wrong?

**Comment by renrizzolo** [comment]
I don't know why this is the case, but if you add `selectLabelNumberOfLines={2}`, it shows.
Also if you rotate the device to landscape, then back to portrait, it shows (but then hides the fruit items).
Also, setting any text align seems to resolve it : `styles={{selectToggleText: {textAlign: 'center'}}}`

So the fix is either number of lines or text align on the select text.

**Comment by sommeshEwall** [comment]
After changing the `styles={{selectToggleText: {textAlign: 'left'}}}` its working fine now. Thanks for the needful.
