### ISSUE TITLE
How can I lower the height of the container?

### ISSUE THREAD

**Issue by raphaelluiz128** [renrizzolo/react-native-sectioned-multi-select#158]
How can I lower the height of the container? I ask because I saw that they answered a question stating that it is to use marginTop, but I really want to reduce the size

**Comment by renrizzolo** [comment]
Do you mean the actual modal content?
You need to adjust `styles.container`. by default it fills and uses marginHorizontal and marginVertical to inset it.
It uses `alignSelf: stretch` and `flex: 1`, so you might want ot override those and give it a fixed or percentage height.

**Comment by jbuijgers** [comment]
For anyone looking to size the height of the container based on the items in multi select, I used the following style:

```js
{
  button: {
    flexBasis: "100%"
  },
  container: {
    flex: 0,
    flexDirection: "row",
    alignContent: "center",
    flexWrap: "wrap"
  },
  scrollView: {
    flexBasis: "100%"
  }
}
```

If there is a better way to do this, please let me know.

**Comment by jbuijgers** [comment]
This will create some issues when dealing with long lists which require scrolling though, looking into fixing this.

**Comment by Bilal-Abdeen** [comment]
I wonder if anyone found a solution to make the modal (1) change height dynamically based on the number of items, and (2) have no issues when the list is long and a scroll is necessary.

**Comment by xiiforlearning** [comment]
> I wonder if anyone found a solution to make the modal (1) change height dynamically based on the number of items, and (2) have no issues when the list is long and a scroll is necessary.

You can dynamically adjust marginVertical for container based on how many lines you want. In my case it was only 3. So I set my item height to 35 (35 * 3 = 105), button height to 50. Add both values (105 + 50) and subtract it from height of screen. At the very end I divided my result by 2 to place everything in the center.

```
const { width, height } = Dimensions.get('screen');

styles={{
  container: {
    marginVertical: (height - 155) / 2,
  },
  item: {
    height: 35,
  }, 
  button: {
    backgroundColor: '#00717f', 
    height: 50,
  }
}}
```
@raphaelluiz128 @jbuijgers
