### ISSUE TITLE
How to open programaticaly?

### ISSUE THREAD

**Issue by HC-Team** [renrizzolo/react-native-sectioned-multi-select#16]
Can I open only the Modal without displaying the Select?

**Comment by renrizzolo** [comment]
@HC-Team You can access the method to display the modal through the ref
`this.SectionedMultiSelect._toggleSelector() `

(define the ref on the SectionedMultSelect component):
` ref={SectionedMultiSelect => this.SectionedMultiSelect = SectionedMultiSelect}`

as for not showing the select, I'll add a bool prop for (not) showing the select component.

**Comment by renrizzolo** [comment]
`hideSelect` added in the latest version.
