### ISSUE TITLE
how to select multiple parents and single child from each of them (like multiple radio groups)

### ISSUE THREAD

**Issue by ghost** [renrizzolo/react-native-sectioned-multi-select#160]

**Comment by renrizzolo** [comment]
I don't think this is possible but I might be misunderstanding. 
Basically you would want only a single child from each parent to be selectable? Would selecting the parent itself enable/disable selecting of its children?

**Comment by hanaechahid** [comment]
Hi @renrizzolo,

I want to save each selected child from each parent in object, how can I do that ?
this is items object:
```
items = [
{
    name: "demo",
   id: 32,
   children: [
         {id: 1, name: "manager"},
         {id: 2, name: "collaborateur"}
   ]
},
{
    name: "demo 2",
   id: 26,
   children: [
         {id: 5, name: "dev"},
         {id: 3, name: "soudeur"}
   ]
},
];
```

what I want is return an array like this: 
```
[
 {id: 32, selectedItems: [ 1 , 2],// here If a selected the children with id 1 and 2
{id: 26, selectedItems: [] // if I didn't select any child 
]
```

thank you
