### ISSUE TITLE
How to get object or id of item I just selected?

### ISSUE THREAD

**Issue by hieunguyendut** [renrizzolo/react-native-sectioned-multi-select#162]
For example I have init list as below:
![Screenshot 2020-01-07 at 14 56 06](https://user-images.githubusercontent.com/30219446/71878356-093e8300-315e-11ea-8ec2-dacb7728bef5.png)
and I select 2 news items dinner and snacks as image below:
![Screenshot 2020-01-07 at 14 58 17](https://user-images.githubusercontent.com/30219446/71878413-27a47e80-315e-11ea-9845-511df67c4274.png)
How can I get 2 new items I just added?(for handle some thing like update some field in it to use some where else)
Thank you so much

**Comment by renrizzolo** [comment]
You receive the ids of what is selected in the `onSelectedItemsChange` function.

If you want to get the difference between each open/close of the selector, record the selected items in the `onToggleSelector` function.

```js
onToggleSelector = (toggled) => {
    toggled
      ? this.setState({ prevItems: this.state.selectedItems })
      : this.setState({ currentItems: this.state.selectedItems });
  };
```

Then you would have 2 arrays, `prevItems` and `currentItems` that you could filter to find what changed, or whatever you need to do.
