### ISSUE TITLE
onSelectedItemObjectsChange does not work

### ISSUE THREAD

**Issue by trev91** [renrizzolo/react-native-sectioned-multi-select#163]
_Originally posted by @trev91 in https://github.com/renrizzolo/react-native-sectioned-multi-select/issues/20#issuecomment-574738519_

I've also attempted using this function as described in your example in the link above. I believe something has broken recently that's causing this function to not work as expected. I keep getting a `onSelectedItemsChange` is not a function, error. It is indeed marked as a required prop, so I tested going into your library and making it not required, but then found myself getting into a rabbit hole of other errors. Are you able to use this `onSelectedItemObjectsChange` as you'd expect @renrizzolo ?

**Comment by renrizzolo** [comment]
Hi @trev91 
`onSelectedItemObjectsChange` is not an alternative to `onSelectedItemsChange`, it is a helper to receive the objects back.
The library relies on the array of ids you pass in `selectedItems` to know what's selected. So if you only used `onSelectedItemObjectsChange` you'd have to filter those objects to create the array of ids, which is unnecessarily complicated.

**Comment by trev91** [comment]
Thanks for the clarification. Much appreciated!
