### ISSUE TITLE
Not fill full height on android

### ISSUE THREAD

**Issue by hieunguyendut** [renrizzolo/react-native-sectioned-multi-select#164]
It working perfectly on iOs but It not get full height of screen on android for some device that have big screen.
Anyone get this error?
Thank you so much.
![error](https://user-images.githubusercontent.com/30219446/72785927-e54f6700-3c5e-11ea-9417-ee90dfc1d83b.png)

**Comment by renrizzolo** [comment]
Have you tried ` modalWithSafeAreaView={true}`?

**Comment by EvvC** [comment]
Hi. I had the same problem on Android and modalWithSafeAreaView didn't help. Fixed it with adding min-height style to modal wrapper
 
```
import { Dimensions } from 'react-native'
import SectionedMultiSelect from 'react-native-sectioned-multi-select'

<SectionedMultiSelect
    styles={{
        modalWrapper: {
            minHeight: Dimensions.get('window').height, 
         }
    }}
/>
