### ISSUE TITLE
Custom search results not updating in flatlist

### ISSUE THREAD

**Issue by RameshDev92** [renrizzolo/react-native-sectioned-multi-select#165]
Hi ,

I have changed  the logic inside _filterItems method as per my requirement and returning the array of search results but the flat list is not updating with the returned from this method.

Am i missing anything.

my code :

_filterItems = (searchTerm) => {
    const {
      items, subKey, uniqueKey, displayKey, filterItems,
    } = this.props
    if (filterItems) {
      return filterItems(searchTerm, items, this.props)
    }
    let filteredItems = []
    let newFilteredItems = []
    items &&
      items.forEach((item) => {
        const parts = searchTerm
          .replace(/[\^$\\.*+?()[\]{}|]/g, '\\$&')
          .trim()
          .split(' ')
        const regex = new RegExp(`(${parts.join('|')})`, 'i')

        if (regex.test(this.getProp(item, displayKey))) {
          console.log("11111")
          filteredItems.push(item)
        }
        if (item[subKey]) {
          const newItem = Object.assign({}, item)
          newItem[subKey] = []
          item[subKey].forEach((sub) => {
            // if (regex.test(this.getProp(sub, displayKey))) {
            //   newItem[subKey] = [...newItem[subKey], sub]
            //   newFilteredItems = this.rejectProp(
            //     filteredItems,
            //     singleItem => item[uniqueKey] !== singleItem[uniqueKey],
            //   )
            //   newFilteredItems.push(newItem)
            //   filteredItems = newFilteredItems
            // }
            if (regex.test(this.getProp(sub, displayKey))){
            if (sub.firstname.toLowerCase().includes(searchTerm.toLowerCase())
            || (sub.email != undefined && sub.email.includes(searchTerm.toLowerCase()))) {
            newItem[subKey] = [...newItem[subKey], sub]
            newFilteredItems = this.rejectProp(
              filteredItems,
              singleItem => item[uniqueKey] !== singleItem[uniqueKey],
            )
            newFilteredItems.push(newItem)
            filteredItems=newFilteredItems;
            }
            
          }
          })
        }
      })

//If i log filteredItems it is showing correct data but the flatlist is not showing this data.
    return filteredItems
  } 

I have two records called Aaron grainger and Aaron T grainger.

1.when i typed Aaron it is returning 3 records.

![Screenshot_20200125-182134 1](https://user-images.githubusercontent.com/47237110/73121435-236ec280-3fa0-11ea-817d-a98e4fead211.png)

2. When i enter another character which is not in the list it is showing no results.
 
![Screenshot_20200125-182152 1](https://user-images.githubusercontent.com/47237110/73121467-63ce4080-3fa0-11ea-9bc7-83b5103d0a78.png)

3.Now when i remove the last character it is showing correct matching data in the list.

![Screenshot_20200125-182200 1](https://user-images.githubusercontent.com/47237110/73121481-86f8f000-3fa0-11ea-8849-51cd144d4879.png)

**After No results found message the search is working.**

Any help would be appreciated.

Thank you.

**Comment by renrizzolo** [comment]
I wasn't able to reproduce this, are you on the latest version?
I think there were a couple of bugs with the default filter in the past.

It's not clear which are parent or sub items here, or what the displayKey is / structure of the items.

When you loop through the sub items, there is some conflicting logic where it has to pass the regex on the sub item's display key, then it checks if firstname or email includes the searchTerm. Maybe it's not relevant but I don't think you'll be able to search by email without removing the regex test there?

Also, pass your filter function to the `filterItems` prop so you don't have to edit the source code.

I converted it to work as a prop, and it is working fine for me...
The only real change is joining the search parts with space instead of `|`. 
If you join on `|`, you will get both Aarons when you search `Arron T` because the regex is matching `Aaron` OR `T`. This would not be the cause of your issues though, and you may not want to actually do that.

```JS
 
  filterItems = (searchTerm, items, props) => {

    const { subKey, uniqueKey, displayKey } = props;

    let filteredItems = [];
    let newFilteredItems = [];
    items &&
      items.forEach((item) => {
        const parts = searchTerm
          .replace(/[^$\.*+?()[]{}|]/g, '$&')
          .trim()
          .split(' ');
        const regex = new RegExp(`(${parts.join(' ')})`, 'i');
        if (regex.test(item[displayKey])) {
          console.log('11111');
          filteredItems.push(item);
        }
        if (item[subKey]) {
          const newItem = Object.assign({}, item);
          newItem[subKey] = [];
          item[subKey].forEach((sub) => {
            if (regex.test(sub[displayKey])) {
              if (
                sub[displayKey].toLowerCase().includes(searchTerm.toLowerCase()) ||
                (sub.email !== undefined &&
                  sub.email.toLowerCase().includes(searchTerm.toLowerCase()))
              ) {
                newItem[subKey] = [...newItem[subKey], sub];
                newFilteredItems = filteredItems.filter(
                  (singleItem) => item[uniqueKey] !== singleItem[uniqueKey]
                );
                newFilteredItems.push(newItem);
                filteredItems = newFilteredItems;
              }
            }
          });
        }
      });
    return filteredItems;
  };
```
