### ISSUE TITLE
Remove "selectedIconComponent" from the parent.

### ISSUE THREAD

**Issue by anurag-ks** [renrizzolo/react-native-sectioned-multi-select#166]
I am using custom Icons for selected and unselected items, but I don't it to be rendered for the parent item, is there a way I can achieve this?

![WhatsApp Image 2020-02-01 at 10 53 08 AM](https://user-images.githubusercontent.com/3973075/73587407-36721d00-44e1-11ea-83be-8ffc38ca6bd1.jpeg)

Thank you.

**Comment by renrizzolo** [comment]
Currently the only way this happens is if you use `readOnlyHeadings`, but then you wouldn't be able to trigger the **Non Veg** item.

Are you using `renderIcons` or `____IconComponent`?
