### ISSUE TITLE
select all the items in a dynamic multiselect

### ISSUE THREAD

**Issue by sagarrs** [renrizzolo/react-native-sectioned-multi-select#167]
hi i want to use a dynamic mutiselect, on click of the first option in the first dropdown the 2nd dropdown loads dynamically.

i want to select all the selected items of all the dropdown options which is not happenning right now. Please run the below expo snack in your device to know the issue

https://snack.expo.io/@sagar293/select-all-the-items-

**Comment by renrizzolo** [comment]
I'm having trouble understanding the goal/issue here, but if you want to select everything after the items have been changed, try using the `setState` callback
you code 
```JS
this.setState({
 items: a,
}, 
 this.SectionedMultiSelect._selectAllItems();
);
```

you could also just change `newSelectItems: [...a.map((a) => a.name)]` instead.
