### ISSUE TITLE
Update schedule 

### ISSUE THREAD

**Issue by allmaxgit** [renrizzolo/react-native-sectioned-multi-select#17]
I am very interested in your component, but I need some more functionality such as onConfirm in `dev`-branch.
So I was glad if I could add custom header component above searchBar.
May I know when changes about onConfirm will in `master`-branch?

**Comment by renrizzolo** [comment]
@allmaxgit soon! Should be able to get to it tomorrow.

**Comment by renrizzolo** [comment]
updated and added `headerComponent`.
