### ISSUE TITLE
Setting default selected Items give error undefined is not object

### ISSUE THREAD

**Issue by fasalir** [renrizzolo/react-native-sectioned-multi-select#173]
I want to set default selected items, so i set the selected items state directly in constructor, but it giving me error undefined is not object. 

version `"react-native-sectioned-multi-select": "^0.7.6"`

![image](https://user-images.githubusercontent.com/19751530/77503663-c6ed2e00-6e90-11ea-9dad-eea904a221de.png)

this is how i set default selected items in constructor:
`constructor(props){
	super(props);
	this.props = props;
	this.state = {
		selectedRooms : [
			{
				"id": "0",
				"name": "Ruang Meeting Deluxe"
			},
			{
				"id": "1",
				"name": "R. Meeting Rajawali edit"
			},
			{
				"id": "2",
				"name": "Room 123 edit"
			}
		]
	};
}`

the items is from server:
`setRoomItem(){ 
	this.setState({
		rooms: [ 
			{ "id": "0", "name": "Ruang Meeting Deluxe" }, 
			{ "id": "1", "name": "R. Meeting Rajawali edit" }, 
			{ "id": "2", "name": "Room 123 edit" }, 
			{ "id": "3", "name": "R. Meeting Grand Cordela" }, 
			{ "id": "4", "name": "R. Meeting Alfa Resort" }, 
			{ "id": "5", "name": "R. Meeting CX 1" } 
		]
	});
}`

`onSelectedRoomChange = selectedRooms => {
	this.setState({ selectedRooms });
}`

`formatForMultiSelect(arr){
		var temp = [];
		arr.filter((item)=> {
			temp.push(item.id)
		})
		return temp;
}`

`<SectionedMultiSelect
	items={this.state.rooms}
	uniqueKey="id"
	subKey="children"
	styles={{
		chipsWrapper: {
			marginBottom: 12
		},
		selectToggle: {
			marginBottom: 8,
			backgroundColor: '#efefef', 
			height: 45,
			padding: 8
		}
	}}
	selectText="Rooms"
	showDropDowns={false}
    onSelectedItemObjectsChange={this.onSelectedRoomChange}
	onSelectedItemsChange={()=> {}}
	selectedItems={this.formatForMultiSelect(this.state.selectedRooms)} />`

**Comment by renrizzolo** [comment]
I think you need to use the `loading` prop, set it to true then to false after your rooms state has been updated from the server. Or make this.state.rooms = [] in the constructor.

just FYI - you don't need to do `formatForMultiSelect`, you can just do
`onSelectedItemsChange={(selectedRooms) => this.setState({selectedRooms})} `

**Comment by fasalir** [comment]
yes i have set the rooms to empty array in constuctor, `rooms : [],` sorry i didnt copy it to my question.

What i need is objects, instead of array of ids, so i try this one, but still get undefined is not an object
`onSelectedItemObjectsChange={(selectedRoomsObj)=> this.setState({selectedRoomsObj})}
							onSelectedItemsChange={(selectedRooms)=> this.setState({selectedRooms})}
							selectedItems={this.state.selectedRooms} />`

**Comment by JKarathiya** [comment]
I am also getting same error when `subKey` not available. MR at https://github.com/renrizzolo/react-native-sectioned-multi-select/pull/185
