### ISSUE TITLE
How to select all items?

### ISSUE THREAD

**Issue by thiennt6** [renrizzolo/react-native-sectioned-multi-select#175]

**Comment by renrizzolo** [comment]
Currently you need to use a ref on `<SectionedMultiSelect/>` and call its `_selectAllItems()`.
 see: https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/master/Recipes.md#select-or-remove-all-items

**Comment by thiennt6** [comment]
Ok thanks.
