### ISSUE TITLE
Getting name and id of the item selected

### ISSUE THREAD

**Issue by jefersonjuliani** [renrizzolo/react-native-sectioned-multi-select#176]
I would like to get the name and id of the selected items

**Comment by renrizzolo** [comment]
You can use `onSelectedItemObjectsChange`, this gives you an array of the original item objects of the selected items.
```
onSelectedItemObjectsChange={(selectedItemObjects) => this.setState({selectedItemObjects})}
```

**Comment by somagonda** [comment]
I want to display only id and name objects instead of whole array...how to filter array
