### ISSUE TITLE
How to preselect Item in a children

### ISSUE THREAD

**Issue by thedentor** [renrizzolo/react-native-sectioned-multi-select#177]
How can I preselect a default item in my first children @renrizzolo ?
 
 For Example : 
![SelectMultiple](https://user-images.githubusercontent.com/24319165/78624866-a5108580-7858-11ea-9f5e-78e224bca1b0.jpg)

**Comment by renrizzolo** [comment]
Whatever you pass to selectedItems will be selected.
E.g if your `uniqueKey` is `"id"`, and the id of Audi is 1, do `selectedItems={[1]}`

**Comment by thedentor** [comment]
Hi @renrizzolo  Try to do what you say.

But instead of selecting an item from the children, the children see check is selected in the motorcycle part.

And when this happened I could not select an item, I was stuck with the check in the children


  ```
 const items = [
      {
        name: 'Autos',
        id: 0,
        children: this.state.Autos,
      },

      {
        name: 'Motos',
        id: 1,
        children: this.state.Motos,
      },
    ];
```

```
<SectionedMultiSelect
          items={items}
          parentChipsRemoveChildren={false}
          uniqueKey='id'
          subKey='children'
          selectChildren={true}
          selectText="Choose some things..."
          showDropDowns={true} 
          showDropDowns={false}
          readOnlyHeadings={true}
          onSelectedItemsChange={this.onSelectedItemsChange}
          selectedItems={[1]}
          confirmText='Confirmar'
          hideSearch={true}
          styles={{
            selectedItemText: {
              color: 'blue',
            },
            selectedSubItemText: {
               color: 'blue',
            },
          }}
        />
```


![SelectedMmm](https://user-images.githubusercontent.com/24319165/78677993-627d9600-78b6-11ea-850c-a44e734535f7.jpg)

**Comment by renrizzolo** [comment]
This is working as expected, the id of `motos` is 1.

**Comment by thedentor** [comment]
Regards @renrizzolo ,
By doing so you are selecting the category (Autos, Motos) not the subcategory(Audi,Pagani..) etc... It is really what I want to achieve.

**Comment by renrizzolo** [comment]
Hi @thedentor, is something unclear? 
You need to (pre) select the id of the child item – you have selected the id of a parent item. 
I don't have your data so I don't know what the id of `Audi` may be.

**Comment by thedentor** [comment]
I was not taking them because my Json was returning the IDs as string. Now it is working properly.
