### ISSUE TITLE
how can i reduce the space between the (^Add Tasks) to the cheaps below and the header above

### ISSUE THREAD

**Issue by baryanuka** [renrizzolo/react-native-sectioned-multi-select#178]
![IMG_20200407_174108](https://user-images.githubusercontent.com/58971753/78683068-7bf30200-78f7-11ea-9e95-e4a064045e58.jpg)

**Comment by baryanuka** [comment]
second Question is: how can i control where the cheaps will be. how can i organize them as i want?
right now it looks totally random and i dont understand how can i control how many will fit in a row or do a list of them

thx

**Comment by renrizzolo** [comment]
You can do everything you want with the styles, there are styles for the chips/chip container and select toggle.
