### ISSUE TITLE
v0.7.7's Typescript fix for onSelectedItemsChange was incorrect

### ISSUE THREAD

**Issue by bgoldsworthy** [renrizzolo/react-native-sectioned-multi-select#181]
The type signature change to this line was incorrect:
https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/db6dc89e48c1e6e83d46cbf9f418eaa0b4aaa7f8/index.d.ts#L42

The most specific the signature can be is`onSelectedItemsChange: (items: any[]) => void;`

When `SectionedMultiSelect` has `single={true}` `item` isn't passed to this function. `[item[uniqueKey]]` is, which may have any type.
https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/master/lib/sectioned-multi-select.js#L539

It would be more consistent if the signature was left as-is and `[item]` was passed, but that would be a breaking change. I'm happy to make either PR.

**Comment by scousino** [comment]
Yeah this fix is still needed. Otherwise you have TS errors
