### ISSUE TITLE
If i keep single = true, Select item not updating

### ISSUE THREAD

**Issue by amitkoranne** [renrizzolo/react-native-sectioned-multi-select#183]
If I set single={true}, I am able to select a single item.
But unable to update default text on the screen.

i.e.
if I set selectText="Select Company" 
It is not getting replaced by items from the selected text. (Selected company )

**Comment by Rana-Muhammad-Amir** [comment]
facing same issue.... any help?

**Comment by memon07** [comment]
have you tried changing readOnlyHeadings from true to false ?
