### ISSUE TITLE
dynamically populate items and want two controls in same screen issue

### ISSUE THREAD

**Issue by manish-shukla01** [renrizzolo/react-native-sectioned-multi-select#189]
i want to get teh list of items from database but when i do that for some reason, it does not show the new items i added. i am using   react hooks to populate the list of items..
getcities and getmodels are two dropdowns i want to populate . also when i have two of these in one single screen, i think there is some conflict between them. showDropDowns={false} is not working properly.
 React.useEffect(()=>{
      async function anyNameFunction() {
          console.log('getting invoked on load');
          await getCities();
          await getModels();
          setrefreshing(false);
        }
        // Execute the created function directly
        anyNameFunction();
      }, []);

**Comment by manish-shukla01** [comment]
i was able to resolve this. it worked after i made the items a property and used react hooks setproperty to populate them.

**Comment by SupriyaPKalghatgi** [comment]
@manish-shukla01 Did you have two picker controls onto single screen?
