### ISSUE TITLE
Bug with confirmButton

### ISSUE THREAD

**Issue by St1ggy** [renrizzolo/react-native-sectioned-multi-select#19]
I've found bug with confirm button when `showCancelButton === false`. I did solve it with adding `style={{ flex: 1 }}` for `Touchable` - container for `View` around cancel and confirm buttons, but I don't want fork library, because you are continuing to develop this component :)
![image](https://user-images.githubusercontent.com/13361661/37818296-42244b34-2eac-11e8-8758-1620a071b93d.png)
With my styles it should be flex-stretched to window width

**Comment by St1ggy** [comment]
![image](https://user-images.githubusercontent.com/13361661/37818404-a477a7ea-2eac-11e8-882e-704f1a14affe.png)

**Comment by renrizzolo** [comment]
@St1ggy Hey, thanks for the heads up. 
Looks like there's a discrepancy with how the flex works between android and iOS. 
I've been testing on android, and it stretches properly by default.

The behaviour is pretty weird. I have decided to remove the flex ratio for the cancel button and just have it a fixed width instead.

I'll make sure to test styles across both OS now!

**Comment by renrizzolo** [comment]
Let me know if you're still having any problems with this
