### ISSUE TITLE
Chips have no padding by default and no min width for the 'x' button

### ISSUE THREAD

**Issue by shamilovtim** [renrizzolo/react-native-sectioned-multi-select#190]
Problem: When a long value is used for the chip, the padding is overwhelmed and the X button disappears off to the side as well.

Ideal functionality: the X button shows, the left and right padding remain visible, the text cuts off with an ellipsis "...".

<img width="415" alt="Screen Shot 2020-07-03 at 7 20 32 PM" src="https://user-images.githubusercontent.com/3495974/86500882-52b10900-bd62-11ea-8842-ed3b7ce5dc21.png">

**Comment by shamilovtim** [comment]
<img width="413" alt="Screen Shot 2020-07-03 at 7 24 39 PM" src="https://user-images.githubusercontent.com/3495974/86500964-e1258a80-bd62-11ea-8744-04dde0adbff6.png">

Here it is when the parent container attempts to constrain the chips. Still no padding.  X icon hangs off the side.

**Comment by renrizzolo** [comment]
The css for chips is not great.
