### ISSUE TITLE
Is it possible to display third level children ?

### ISSUE THREAD

**Issue by azamkth** [renrizzolo/react-native-sectioned-multi-select#191]
Example:
{
        name: 'Fruits',
        id: 0,
        children1: [
            {
                name: 'Apple',
                id: 10,
                children2: [
                    {
                        name: 'Apple something',
                        id: 60,
                    },
                ]    
            },
            {
                name: 'Strawberry',
                id: 17,
            },
        ],
    },

**Comment by renrizzolo** [comment]
Unforutnately this isn't supported. There may be a way to do it yourself with the upcoming version, which has a bit more flexibility for customization.

**Comment by azamkth** [comment]
thanks for you prompt reply. Could you guide me how i can achieve this using your library?

**Comment by renrizzolo** [comment]
I had a look into it, and this is not currently possible, sorry.

**Comment by T0mAl3x** [comment]
Hello!

I managed to do a workaround until a feature with multiple layers of children is avaible.
I copied the source code locally and updated RowItem in FlatList render method:
```
_renderSubItemFlatList = (
    subItem,
    subKey,
    uniqueKey,
    selectedItems,
    subItemsFlatListProps
) => {
    return <View>
      <RowSubItem
        _toggleSubItem={this._toggleSubItem}
        subItem={subItem}
        highlightedChildren={this.props.highlightedChildren}
        {...this.props}
      />
      {subItem[subKey] && (
        <FlatList
          style={{marginStart: 10}}
          keyExtractor={(i) => `${i[uniqueKey]}`}
          data={subItem[subKey]}
          extraData={selectedItems}
          ItemSeparatorComponent={this._renderSubSeparator}
          renderItem={({ item }) =>
            this._renderSubItemFlatList(
              item,
              subKey,
              uniqueKey,
              selectedItems,
              subItemsFlatListProps
            )
          }
          initialNumToRender={20}
          {...subItemsFlatListProps}
        />
      )}
    </View>;
  };
```

FlatList in render method
```
<FlatList
            keyExtractor={(i) => `${i[uniqueKey]}`}
            data={item[subKey]}
            extraData={selectedItems}
            ItemSeparatorComponent={this._renderSubSeparator}
            renderItem={({ item }) =>
              this._renderSubItemFlatList(
                item,
                subKey,
                uniqueKey,
                selectedItems,
                subItemsFlatListProps
              )
            }
            initialNumToRender={20}
            {...subItemsFlatListProps}
          />
```

**Comment by KarasuShin** [comment]
I create a PR to feature it #279
