### ISSUE TITLE
How to toggle this view with a custom button?

### ISSUE THREAD

**Issue by subhadippramanik** [renrizzolo/react-native-sectioned-multi-select#196]
I want to use a custom button which should open/close the modal view. I don't want the select text and arrow keys. Is there a way to do?

I tried using `dropDownToggleIconUpComponent`/`dropDownToggleIconDownComponent` and set my button object, but that didn't work.

**Comment by renrizzolo** [comment]
Hi @subhadippramanik those props you mention refer to the dropdown icon for the parent items within the items list.
For programmatically opening the select modal, use `onPress={() => this.SectionedMultiSelect._toggleSelector()}` on your custom button. 

Note that `this.SectionedMultiSelect` is a ref of your `<SectionedMultiSelect/>` component.

**Comment by gregfenton** [comment]
How would one get a reference to `this` in a functional component?

**Comment by renrizzolo** [comment]
I just did this basic functional component test which seems to work:

```JSX
import React, { useRef, useState } from 'react'
...

const items = [
  {
    title: 'Fruits',
    id: 0,
    children: [
      {
        title: 'Apple',
        id: 10
      },
      {
        title: 'Strawberry',
        id: 11
      },
      {
        title: 'Pineapple',
        id: 13
      },
      {
        title: 'Banana',
        id: 14
      },
     
    ]
  },
]
const App = () => {
  const ref = useRef(null)
  const [selectedItems, setSelectedItems] = useState([])
  console.log('rnsms ref', ref)
  return (
    <View>
      <TouchableOpacity
        onPress={() => ref && ref.current && ref.current._toggleSelector()}>
        <Text>Toggle!</Text>
      </TouchableOpacity>

      <SectionedMultiSelect
        items={items}
        ref={ref}
        selectedItems={selectedItems}
        onSelectedItemsChange={items => setSelectedItems(items)}
        uniqueKey="id"
        subKey="children"
        displayKey="title"
        iconKey="icon"
        iconRenderer={Icon}
      />
    </View>
  )
}
export default App
```

**Comment by gregfenton** [comment]
That's awesome!  Thank you!

Will you add that to docs?  Or want me to push a PR with that example?

**Comment by renrizzolo** [comment]
No worries. I'll update the docs now!

**Comment by bmitioglov** [comment]
> I just did this basic functional component test which seems to work:
> 
> ```js
> import React, { useRef, useState } from 'react'
> ...
> 
> const items = [
>   {
>     title: 'Fruits',
>     id: 0,
>     children: [
>       {
>         title: 'Apple',
>         id: 10
>       },
>       {
>         title: 'Strawberry',
>         id: 11
>       },
>       {
>         title: 'Pineapple',
>         id: 13
>       },
>       {
>         title: 'Banana',
>         id: 14
>       },
>      
>     ]
>   },
> ]
> const App = () => {
>   const ref = useRef(null)
>   const [selectedItems, setSelectedItems] = useState([])
>   console.log('rnsms ref', ref)
>   return (
>     <View>
>       <TouchableOpacity
>         onPress={() => ref && ref.current && ref.current._toggleSelector()}>
>         <Text>Toggle!</Text>
>       </TouchableOpacity>
> 
>       <SectionedMultiSelect
>         items={items}
>         ref={ref}
>         selectedItems={selectedItems}
>         onSelectedItemsChange={items => setSelectedItems(items)}
>         uniqueKey="id"
>         subKey="children"
>         displayKey="title"
>         iconKey="icon"
>         iconRenderer={Icon}
>       />
>     </View>
>   )
> }
> export default App
> ```

it's a bit weird but modal started to appear more slowly on the screen when I use custom button to toggle selector. Do you know what might be the reason?

**Comment by msaadqureshi** [comment]
> 

How i can use this as a component to call multiple Screens
