### ISSUE TITLE
How to deselect an item when single={true}

### ISSUE THREAD

**Issue by gregfenton** [renrizzolo/react-native-sectioned-multi-select#199]
If we set `single={true}`, and the user selects a value, how can the user "deselect" their value?  I have tried the following approaches to no avail:
- enable `showCancelButton` and click it - the value remains selected
- open the modal and select the value a second time - the value remains selected
- open the modal and simply click the "confirm" button - the value remains selected

How does a user unset (or "deselect") once a value is chosen?

**Comment by gregfenton** [comment]
Nudge?  Anyone?  Bueller??

Any pointer on where in the code to start looking, if I were to make a change and a PR?

**Comment by renrizzolo** [comment]
I don't think this is something that's built into the lib, from memory. 

The code for single selection is here https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/db6dc89e48c1e6e83d46cbf9f418eaa0b4aaa7f8/lib/sectioned-multi-select.js#L537-L541

Here's what I'd do (untested), given that you know only 1 item can be selected at a time when using `single`.

```js
 onSelectedItemsChange = (selectedItems) => {
   if (this.state.selectedItems[0] === selectedItems[0]) {
     // that item is selected, deselect it
     this.setState({ selectedItems: [] });
   } else { 
     this.setState({ selectedItems });
    }
  };
```

If you wanted to implement this with the cancel button, you need to add your own `onCancel` callback.

You could also just add your own  clear selection button next to the select (for example) that resets the `selectedItems` state.

**Comment by gregfenton** [comment]
Brilliant!  Not sure why I didn't see that myself.

I am dynamically generating a form based on a "type" set in a data-driven configuration.  The type indicates if the field is multi-select or single-select.  So my one "SelectionPicker" component is handling both cases.

I'm using react-hook-form (RHF).  Here is what I have, now working(!!!!), thanks to @renrizzolo's input:

```
let DEFAULT_VALUE = '';

<Controller
  control={rhfControl}
  name={rhfFieldId}
  rules={{
    required: true,
  }}
  defaultValue={initialValue}
  render={({value: rhfValue, onChange: rhfOnChange}) => (
        <SectionedMultiSelect
          items={fieldOptions}
          uniqueKey="id"
          displayKey="name"
          selectedItems={
            rhfValue === DEFAULT_VALUE ? [] : rhfValue
          }
          single={isSingle}
          showCancelButton={true}
          onCancel={() => {rhfOnChange(DEFAULT_VALUE)}}
          onSelectedItemsChange={(selectedIndexes) => {
            if (isSingle) {
              if (selectedIndexes[0] === rhfValue[0]) {
                // clicked same value, so de-select it
                rhfOnChange(DEFAULT_VALUE);
              } else {
                rhfOnChange(selectedIndexes);
              }
            } else {
              if (selectedIndexes.length <= 0) {
                // no values selected
                rhfOnChange(DEFAULT_VALUE);
              } else {
                rhfOnChange(selectedIndexes);
              }
            }
          }}
          ref={(component) => setMultiSelect(component)}
          colors={{
            chipColor: 'blue',
            success:  'blue',
            primary:  'blue',
          }}
          styles={{
            selectToggle: {
              backgroundColor:
                _.isEqual(initialValue, rhfValue) &&
                initialValue === DEFAULT_VALUE
                  ? 'grey'
                  : 'blue',
              borderRadius: 4,
              paddingHorizontal: 5,
              marginBottom: 5,
            },
            parentChipContainer: {borderColor: 'red', borderWidth: 1},
            modalWrapper: {justifyContent: 'center'},
            container: {flex: containerFlex},
          }}
          searchInputStyle={styles.searchInput}
          hideSearch={!fieldEnableSearch}
          confirmText={
            isSingle
              ? 'Close Dialog'
              : 'Confirm Choice'
          }
          selectText={"Select"}
          searchPlaceholderText={"Search"}
          {...rest}
        />
    )}
/>
```

Hopefully this is of use to others.

Thank you @renrizzolo !!

**Comment by renrizzolo** [comment]
Glad that sorted it out @gregfenton !
