### ISSUE TITLE
Prop to disable search

### ISSUE THREAD

**Issue by ziyafenn** [renrizzolo/react-native-sectioned-multi-select#2]
Hi there! First of all, thank you soooo much for this component, best modal dropdown so far! 
Really glad that found it!

Would be cool if it would be possible to disable search as it's not always needed.

Thanks a lot!!

**Comment by ziyafenn** [comment]
And by the way, i'm having a problem with applying defined class from StyleSheet as a style. 
Can you please give an example how to do it correct?

**Comment by renrizzolo** [comment]
Hi @ziyafenn, 
Thanks for the suggestion, I've added a ``hideSearch`` prop which defaults to false.

for single styles this should work:
```

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#f8f8f8',
  },
});

<SectionedMultiSelect
...
styles={{
  container: styles.container,
}}
...
SectionedMultiSelect/>
```

or you could put in a whole stylesheet ``styles={styles}``

or mix them: 
```
styles={[{
    button: {
    borderRadius: 0,
    backgroundColor:'#e1e1e1', 
  }}, styles]}
```
