### ISSUE TITLE
Icons are overridden if multiple selects are displayed on the same page

### ISSUE THREAD

**Issue by bmaximilian** [renrizzolo/react-native-sectioned-multi-select#203]
### Current State
* A component renders a form with multiple SectionedMultiSelect
* Some selects receive the prop `iconRenderer` some don't (even more problematic if there are different `iconRenderer`s)
* The `iconRenderer` of the component that is constructed last is applied to all SectionedMultiSelect that are rendered

### Desired State
* A component renders a form with multiple SectionedMultiSelect
* The `iconRenderer` of the select is only applied to the component that receives it as prop

### Info
In line 22, icon is defined globally. The constructor of the select assigns the `iconRenderer` or the MaterialIcons to the Icon variable.
This icon variable is assigned multiple times if multiple selects are rendered.

**Comment by renrizzolo** [comment]
fixed in 0.8.0
