### ISSUE TITLE
Crash on showChips={true}

### ISSUE THREAD

**Issue by princealir** [renrizzolo/react-native-sectioned-multi-select#205]
Logs are giving proper values. What could be the cause?

iOS 14.0.1

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

```
const dummyList=[
        {id: 5, name: "Moodiness"},
        {id: 9, name: "Corona Virus"},
        {id: 10, name: "vomiting"},
        {id: 11, name: "weight loss and poor appetite."},
        {id: 12, name: "shortness of breath."},
        {id: 13, name: "Tiredness."}
    ]

const [selectedSymptoms,setSelectedSymptoms]=useState([]);
const symptomsList = dummyList ? [{ name : "Symptoms" , id: 0 , children: dummyList }] : [{ name : "Symptoms" , id: 0 , children: [] }];

<SectionedMultiSelect
 styles={{ selectToggleText:{fontSize:12, color:textPrimaryColor, fontFamily:'Roboto-Medium'}, selectToggle:{padding:0, paddingTop:5}, confirmText:{fontSize:18, fontFamily:'Roboto-Bold'}, button:{backgroundColor:brandColor}, chipContainer:{borderColor:brandColor}, chipText:{fontSize:12, color:textPrimaryColor, fontFamily:'Roboto-Light'}, itemText:{fontSize:16, fontFamily:'Roboto-Bold', color:textSecondaryColor}, subItemText:{fontSize:14, fontFamily:'Roboto-Bold', color:textPrimaryColor}}}
                            items={symptomsList}
                            uniqueKey="id"
                            subKey="children"
                            searchPlaceholderText="Search symptoms"
                            selectText="Select your symptoms"
                            showDropDowns={false}
                            readOnlyHeadings={true} showChips={true}
                            onSelectedItemsChange={(selectedItem)=>{ setSelectedSymptoms(selectedItem); }}
                            selectedItems={selectedSymptoms}
                        />

```

**Comment by TheMarcusLee** [comment]
I'm also having this issue on new install. I have this package setup in another project from a couple of weeks ago with no issues. This seems to have just come about in the last week or so.

**Comment by princealir** [comment]
@LegaciPro I solved it by downgrading to 0.7.7

The issue is in version 0.7.8.
Tried 0.7.7 and it is working fine.

**Comment by TheMarcusLee** [comment]
@technyx-ali-rehman Thanks I also reverted to 0.7.7 and it is working fine in my application.

**Comment by renrizzolo** [comment]
I'll revert or try to fix it.

**Comment by renrizzolo** [comment]
Along with the issue that this bug was trying to fix (#203), relying on `react-native-vector-icons` has been a bit of a pain point, so I've decided to make `IconRenderer` mandatory.
Here's the PR, please let me know if there are any problems: https://github.com/renrizzolo/react-native-sectioned-multi-select/pull/206

Unfortunately this is a breaking change, you will now need to pass an `Icon` component to `IconRenderer`. I've detailed the change in the Readme of the PR.

**Comment by TheMarcusLee** [comment]
I've implemented v0.8.0 in my application with no issues. Thank you!

**Comment by princealir** [comment]
@renrizzolo 
undefined is not an object (evaluating 'item[subKey]')
get this on 0.8.0 on showChips={true}

@LegaciPro 
Is there a work arount to this ?

**Comment by mohity777** [comment]
This issue is occuring in V 0.7.6 also. It works fine in android but crash on IOS with same error.
