### ISSUE TITLE
Having two subkeys 

### ISSUE THREAD

**Issue by TajSinghESGI** [renrizzolo/react-native-sectioned-multi-select#208]
Hi i wanted to know if it is possible to have two subkeys list ? So basically i have my parents and then i have my childrens. But in the the children i want to have an another child array. Is it possible ? Thanks a lot in advance !

**Comment by renrizzolo** [comment]
Sorry this isn't possible - there is only 1 level (parents > children).

**Comment by TajSinghESGI** [comment]
Thanks for your answer !
