### ISSUE TITLE
IconRenderer type error with Material Icons and Icon

### ISSUE THREAD

**Issue by jota12x** [renrizzolo/react-native-sectioned-multi-select#211]
I am importing the MateriaI_Icons from Expo and setting them in the `IconRenderer` attribute
`import {MaterialIcons} from '@expo/vector-icons';`

However, there is a compilation warning from Typescript. The example is written similarly to the official documentation, so I wonder if there has been some update from the dependencies (vector-icons).

![imagen](https://user-images.githubusercontent.com/6154802/96078904-79004c00-0eee-11eb-9dc2-e038c7bd0a0a.png)

Below is my current package.json and to be clear I am using the latest Expo SDK (v39).
` 

    "@expo/vector-icons": "^10.2.1",
    "@react-native-community/datetimepicker": "3.0.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/picker": "^1.6.6",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/material-top-tabs": "^5.2.13",
    "@react-navigation/native": "^5.7.0",
    "@react-navigation/native-stack": "^5.0.5",
    "@react-navigation/stack": "^5.9.0",
    "@types/shortid": "^0.0.29",
    "@types/uuid": "^8.3.0",
    "axios": "^0.20.0",
    "dotenv": "^8.2.0",
    "events": "^3.1.0",
    "expo-secure-store": "~9.2.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-hook-form": "^6.9.2",
    "react-native": "0.63.3",
    "react-native-form-select-picker": "^0.0.9",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-get-random-values": "^1.5.0",
    "react-native-modal-datetime-picker": "^9.0.0",
    "react-native-paper": "^4.2.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-screens": "~2.10.1",
    "react-native-sectioned-multi-select": "^0.8.0",
    "react-native-tab-view": "^2.14.4",
    "react-native-table-component": "^1.2.1",
    "react-native-unimodules": "~0.11.0",
    "react-native-vector-icons": "^7.0.0",
    "react-native-web": "~0.13.7",
    "react-native-webview": "10.7.0",
    "react-redux": "^7.2.0",
    "redux-saga": "^1.1.3",
    "short-id": "^0.1.0-1",
    "uuid": "^8.3.1"
`

**Comment by renrizzolo** [comment]
so, the iconRenderer is expecting `(() => void) | JSX.Element`
It's defined here: https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/master/index.d.ts

I don't do enough TS to know the answer.. I think we may need to change the `JSX.Element`(s) to `ReactElement | null`.

**Comment by jota12x** [comment]
> so, the iconRenderer is expecting `(() => void) | JSX.Element`
> It's defined here: https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/master/index.d.ts
> 
> I don't do enough TS to know the answer.. I think we may need to change the `JSX.Element`(s) to `ReactElement | null`.

Yes, that seems good enough.  What was the version of `expo-vector-icons` used for the documentation? Maybe I will downgrade just to make sure.

**Comment by renrizzolo** [comment]
Sorry I'm not sure, that was a contribution #207 @gregfenton

**Comment by gregfenton** [comment]
That was done with expo SDK 38.  I also don't do TS so can't help on that front.

**Comment by jota12x** [comment]
I tested it again after deleting the cache and now is working so I will close the issue. Thanks for your time !

**Comment by luvever-app** [comment]
Still getting same TS error as OP, by implementing example from main readme. 
4 years later. Is this repo maintained?
