### ISSUE TITLE
More than 3 selections messes up the Layout

### ISSUE THREAD

**Issue by Vijay1126** [renrizzolo/react-native-sectioned-multi-select#214]
Expected:

![image](https://user-images.githubusercontent.com/63943580/96508130-2396a880-1228-11eb-9e08-6f8394090af2.png)

Problem:
![image](https://user-images.githubusercontent.com/63943580/96507940-e205fd80-1227-11eb-94bb-d47c124e7d61.png)

How do I make sure the layout remains the same? 
Code:
```
import React, { Component } from 'react';
import { View } from 'react-native';
import SectionedMultiSelect from 'react-native-sectioned-multi-select';
import { Ionicons } from '@expo/vector-icons';

const items = [
  // this is the parent or 'item'
  {
    name: 'Underlying Conditions',
    id: 0,
    // these are the children or 'sub items'
    children: [
      {
        name: 'Cardiomegaly',
        id: 10,
      },
      {
        name: 'Arrhythmia',
        id: 17,
      },
      {
        name: 'Heart stroke',
        id: 13,
      },
      {
        name: 'Atrial fibrillation',
        id: 14,
      },
    ],
  },
 
];

export default class MultiSelectDropdown extends Component {
  constructor() {
    super();
    this.state = {
      selectedItems: [],
    };
  }
  onSelectedItemsChange = (selectedItems) => {
    this.setState({ selectedItems });
  };

  render() {
    return (
      <View>
        <SectionedMultiSelect
          showDropDowns={false}
          expandDropDowns={true}
          items={items}
          uniqueKey="id"
          subKey="children"
          selectText="Underlying Conditions"
          showDropDowns={true}
          readOnlyHeadings={true}
          onSelectedItemsChange={this.onSelectedItemsChange}
          selectedItems={this.state.selectedItems}
          selectToggleIconComponent = {<Ionicons name="md-arrow-dropdown" size={24} color="black" style={{marginRight:12}}/>}
          styles={{ 
            button:{backgroundColor:'#759D75'}, 
            container: {
              paddingTop: 20,
              width: '90%',
              height: '60%',
              flex: 0,
              alignSelf: 'center',
              justifyContent: 'center',
              top: '10%'
            },
            selectToggle:{ borderWidth: 1, width: 325, borderRadius: 5, height: 38, marginTop: 7, backgroundColor: "#f6f6f6", borderColor: "#737373"},
            selectToggleText: { fontSize:16, marginStart: 13, fontFamily: 'Roboto', color: "rgba(67, 67, 67, 0.75)", marginTop: 12}
          }  
        }
        />
      </View>
    );
  }
}
```

**Comment by Vijay1126** [comment]
`import React, { Component } from 'react';
import { View } from 'react-native';
import SectionedMultiSelect from 'react-native-sectioned-multi-select';
import { Ionicons } from '@expo/vector-icons';

const items = [
  // this is the parent or 'item'
  {
    name: 'Underlying Conditions',
    id: 0,
    // these are the children or 'sub items'
    children: [
      {
        name: 'Cardiomegaly',
        id: 10,
      },
      {
        name: 'Arrhythmia',
        id: 17,
      },
      {
        name: 'Heart stroke',
        id: 13,
      },
      {
        name: 'Atrial fibrillation',
        id: 14,
      },
    ],
  },
 
];

export default class MultiSelectDropdown extends Component {
  constructor() {
    super();
    this.state = {
      selectedItems: [],
    };
  }
  onSelectedItemsChange = (selectedItems) => {
    this.setState({ selectedItems });
  };

  render() {
    return (
      <View>
        <SectionedMultiSelect
          showDropDowns={false}
          expandDropDowns={true}
          items={items}
          uniqueKey="id"
          subKey="children"
          selectText="Underlying Conditions"
          showDropDowns={true}
          readOnlyHeadings={true}
          onSelectedItemsChange={this.onSelectedItemsChange}
          selectedItems={this.state.selectedItems}
          selectToggleIconComponent = {<Ionicons name="md-arrow-dropdown" size={24} color="black" style={{marginRight:12}}/>}
          styles={{ 
            button:{backgroundColor:'#759D75'}, 
            container: {
              paddingTop: 20,
              width: '90%',
              height: '60%',
              flex: 0,
              alignSelf: 'center',
              justifyContent: 'center',
              top: '10%'
            },
            selectToggle:{ borderWidth: 1, width: 325, borderRadius: 5, height: 38, marginTop: 7, backgroundColor: "#f6f6f6", borderColor: "#737373"},
            selectToggleText: { fontSize:16, marginStart: 13, fontFamily: 'Roboto', color: "rgba(67, 67, 67, 0.75)", marginTop: 12}
          }  
        }
        />
      </View>
    );
  }
}`

**Comment by Vijay1126** [comment]
[import React, { Component } from 'react';
import { View } from 'react-native';
import SectionedMultiSelect from 'react-native-sectioned-multi-select';
import { Ionicons } from '@expo/vector-icons';

const items = [
  // this is the parent or 'item'
  {
    name: 'Underlying Conditions',
    id: 0,
    // these are the children or 'sub items'
    children: [
      {
        name: 'Cardiomegaly',
        id: 10,
      },
      {
        name: 'Arrhythmia',
        id: 17,
      },
      {
        name: 'Heart stroke',
        id: 13,
      },
      {
        name: 'Atrial fibrillation',
        id: 14,
      },
    ],
  },
 
];

export default class MultiSelectDropdown extends Component {
  constructor() {
    super();
    this.state = {
      selectedItems: [],
    };
  }
  onSelectedItemsChange = (selectedItems) => {
    this.setState({ selectedItems });
  };

  render() {
    return (
      <View>
        <SectionedMultiSelect
          showDropDowns={false}
          expandDropDowns={true}
          items={items}
          uniqueKey="id"
          subKey="children"
          selectText="Underlying Conditions"
          showDropDowns={true}
          readOnlyHeadings={true}
          onSelectedItemsChange={this.onSelectedItemsChange}
          selectedItems={this.state.selectedItems}
          selectToggleIconComponent = {<Ionicons name="md-arrow-dropdown" size={24} color="black" style={{marginRight:12}}/>}
          styles={{ 
            button:{backgroundColor:'#759D75'}, 
            container: {
              paddingTop: 20,
              width: '90%',
              height: '60%',
              flex: 0,
              alignSelf: 'center',
              justifyContent: 'center',
              top: '10%'
            },
            selectToggle:{ borderWidth: 1, width: 325, borderRadius: 5, height: 38, marginTop: 7, backgroundColor: "#f6f6f6", borderColor: "#737373"},
            selectToggleText: { fontSize:16, marginStart: 13, fontFamily: 'Roboto', color: "rgba(67, 67, 67, 0.75)", marginTop: 12}
          }  
        }
        />
      </View>
    );
  }
}](url)

**Comment by renrizzolo** [comment]
It's hard to say what's causing this, you might need to put a width or flex value on `chipsWrapper`.
Alternatively try applying styles (e.g width :100%) to the view that you're wrapping the SectionedMultiSelect component.

**Comment by Vijay1126** [comment]
`import React, { Component } from 'react';
import { View } from 'react-native';
import SectionedMultiSelect from 'react-native-sectioned-multi-select';
import { Ionicons } from '@expo/vector-icons';

const items = [
  // this is the parent or 'item'
  {
    name: 'Underlying Conditions',
    id: 0,
    // these are the children or 'sub items'
    children: [
      {
        name: 'Cardiomegaly',
        id: 10,
      },
      {
        name: 'Arrhythmia',
        id: 17,
      },
      {
        name: 'Heart stroke',
        id: 13,
      },
      {
        name: 'Atrial fibrillation',
        id: 14,
      },
    ],
  },
 
];

export default class MultiSelectDropdown extends Component {
  constructor() {
    super();
    this.state = {
      selectedItems: [],
    };
  }
  onSelectedItemsChange = (selectedItems) => {
    this.setState({ selectedItems });
  };

  render() {
    return (
      <View styles ={{width: "100%"}}>
        <SectionedMultiSelect
          showDropDowns={false}
          expandDropDowns={true}
          items={items}
          uniqueKey="id"
          subKey="children"
          selectText="Underlying Conditions"
          showDropDowns={true}
          readOnlyHeadings={true}
          onSelectedItemsChange={this.onSelectedItemsChange}
          selectedItems={this.state.selectedItems}
          selectToggleIconComponent = {<Ionicons name="md-arrow-dropdown" size={24} color="black" style={{marginRight:12}}/>}
          styles={{ 
            button:{backgroundColor:'#759D75'}, 
            container: {
              paddingTop: 20,
              width: '90%',
              height: '60%',
              flex: 0,
              alignSelf: 'center',
              justifyContent: 'center',
              top: '10%'
            },
            selectToggle:{ borderWidth: 1, width: 325, borderRadius: 5, height: 38, marginTop: 7, backgroundColor: "#f6f6f6", borderColor: "#737373"},
            selectToggleText: { fontSize:16, marginStart: 13, fontFamily: 'Roboto', color: "rgba(67, 67, 67, 0.75)", marginTop: 12}
          }  
        }
        />
      </View>
    );
  }
}`
