### ISSUE TITLE
Getting an error while selecting an item in the latest version.

### ISSUE THREAD

**Issue by raghav1299** [renrizzolo/react-native-sectioned-multi-select#216]
![Screenshot_1603706823](https://user-images.githubusercontent.com/52759313/97159918-94e2d800-17a1-11eb-81de-03983edd9592.png)
Getting the above error while i am trying to select an item from the drop down. This error was not there in the previous version.
currently i am using 0.8.0.

**Comment by ramprakashreddy** [comment]
Even I am Facing the same issue

**Comment by xtealer** [comment]
What version of react-native do you have installed?
