### ISSUE TITLE
Custom selected item

### ISSUE THREAD

**Issue by bbaoNg97** [renrizzolo/react-native-sectioned-multi-select#220]
Hi, 

How do i customize the selected item? for example i would like to disable one selected item if status is pending, else just show like normal.

Thanks

**Comment by renrizzolo** [comment]
You can add `disabled: true` to the item itself. This will make the item unselectable, but it won't have an effect on already selected items. 
If you need to programattically unselect an item, you can do that in any way you like as you have control of the `selectedItems` state.

**Comment by bbaoNg97** [comment]
ok got it, thankss
