### ISSUE TITLE
fetch data in filterItems

### ISSUE THREAD

**Issue by lisandrolan** [renrizzolo/react-native-sectioned-multi-select#221]
Hi, 
I would like to fetch users when something is written in the search area. 
I implemented a fetch in filterItems but it is not working. 
If i have the initial item array empty and return something in filterItems, i dont get any result in the FlatList. 

Any clues?

TYA

**Comment by renrizzolo** [comment]
This isn't something I've tried to do, but in theory you can update your items array from the filterItems function. In practice filterItems isn't designed to do this kind of autocomplete/data retreival, so you might have some ux issues with it.
Looking at the code, I think you need to both set the items and return them in filterItems.
```js
function myComponent () {
 const [items, setItems = useState([])

 // debounce this
 const filter = async (searchTerm) => {
  const results = await fetchStuffFromSomewhere(searchTerm)
  // results: [{id: 1, name: "item 1"}, {id: 2, name: "item 2"}]
  results && results.length > 0 && setItems(results)
  return items;
 }
 return (
  <SectionedMultiSelect items={items} filterItems={filter} {...} />
 )
}
```
