### ISSUE TITLE
Check icon is not showing

### ISSUE THREAD

**Issue by Z33shan4li** [renrizzolo/react-native-sectioned-multi-select#222]
Hi,

I have integrated the package, the selection is working fine but the check icon is not showing. is there any additional change that i need to make?

**Comment by Vivekchudasma** [comment]
Hi,

Selection is not working and the check icon is not showing.

**Comment by sentry0** [comment]
The example is incorrect:

Find the `onSelectedItemChange` prop and change it to the following:

`onSelectedItemsChange={(selected) => this.onSelectedItemsChange(selected)}`

Note, I added in the `selected` param
