### ISSUE TITLE
Android StatusBar and Navigation Bar must be gray background when modal is open

### ISSUE THREAD

**Issue by xdarkleonx** [renrizzolo/react-native-sectioned-multi-select#225]
I have light styled screen with white statusBar background. When I calls modal, background screen becomes gray but statusBar still white. This is not entirely correct behavior and background color of statusBar must be gray too. I think this functionality must be from box but not workaround.

**Comment by GabrielFn** [comment]
i have the same problem

**Comment by renrizzolo** [comment]
This is not something that the Modal component can take care of as far as I know. 
You have to update the statusbar colour when the modal is toggled.

```jsx
const App = () => {
  const [statusBarColor, setStatusBarColor] = useState('white')

  const toggle = bool =>
    bool ? setStatusBarColor('rgba(0,0,0,0.5)') : setStatusBarColor('white')

  return (
    <>
      <StatusBar
        backgroundColor={statusBarColor}
        barStyle={'dark-content'}
        animated
      />
      <View>
        <SectionedMultiSelect
            ...
          onToggleSelector={toggle}
        />
      </View>
    </>
  )
}
```

**Comment by xdarkleonx** [comment]
Same thing with navigation bar color on andoid (phones which have digital bottom buttons). When you open modal, navigation bar color changes to white even if color was black. And trick with onToggleSelector is not working. Any ideas how to fix that?
