### ISSUE TITLE
is there function to limit number of selected???

### ISSUE THREAD

**Issue by daonez** [renrizzolo/react-native-sectioned-multi-select#226]
I understand single=true allows only 1 

but  there seems not to have any min/max or multiple to control the numbers of selected

**Comment by renrizzolo** [comment]
No there is not.
You can do something like this:
https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/master/Recipes.md#limit-selection-count

**Comment by daonez** [comment]
> No there is not.
> You can do something like this:
> https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/master/Recipes.md#limit-selection-count

Thank you I'll have a try
