### ISSUE TITLE
How to run the example app

### ISSUE THREAD

**Issue by JDMathew** [renrizzolo/react-native-sectioned-multi-select#227]
I see there is an example app but there isn't documentation on how to run this if I clone the repo. The example app doesn't seem to have expo but there is also no ios and android folder. How do I run the example app?

**Comment by renrizzolo** [comment]
You would need to create a new React Native project and copy the contents of App.js over.
What's the best approach? I don't have ios/android folders in here because of the size.

**Comment by JDMathew** [comment]
okay, and then I will also the setup of react-native-vector-icons 👍
