### ISSUE TITLE
Can icons props be optionnal?

### ISSUE THREAD

**Issue by DryDemon** [renrizzolo/react-native-sectioned-multi-select#229]
on line 122 in index.d.ts there is the icon props
`  icons: {
    search: {
      name: string
      size: number
    }
....`
Is it possible to set icons as an optional variable? I don't need to change the default setting.
`  icons: {` to `  icons?: {`

**Comment by itzfeltrin** [comment]
yes, please. also, the 'IconRenderer' prop expects a function when it should be just an element. it works fine like this, but the error is annoying me :x
![image](https://user-images.githubusercontent.com/45427460/112056554-e87e0580-8b36-11eb-937a-ddad5e4882da.png)

**Comment by renrizzolo** [comment]
Is this wrong? What should it be?
https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/068ce82c3013f843af8bf8b42e59ceff040117c6/index.d.ts#L116

**Comment by itzfeltrin** [comment]
I don't know, really, just got started with ts. maybe something changed with rn-vector-icons?. I will take a look into that later. anyway, I'd appreciate if you could make the icons prop optional :)

**Comment by itzfeltrin** [comment]
adding React.ReactNode to the IconRenderer prop makes the error go away, I don't know if it's a good solution tho
![image](https://user-images.githubusercontent.com/45427460/112484456-b6e48480-8d58-11eb-9fb4-fcf184b19415.png)

**Comment by scousino** [comment]
the real issue is with the icons prop, not the IconRenderer prop. icons is currently listed as a required prop, but it isn't required, since a default is available.

**Comment by scousino** [comment]
To clarify the IconRenderer typescript error is also valid, just not what the original poster was opening the issue about.

**Comment by JimTeva** [comment]
@renrizzolo , please check https://github.com/renrizzolo/react-native-sectioned-multi-select/pull/253

**Comment by renrizzolo** [comment]
Both issues should be ixed in v0.8.2, please re-open if it persists.

**Comment by jonrainier** [comment]
https://github.com/renrizzolo/react-native-sectioned-multi-select/commit/9cc4df7a24b214c3398e5b7c1e85be463a388115#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8L124

Looks like these changes were reverted in this commit. Not sure if it's intentional or not, but I'm running into the same issues previously mentioned in this thread.
