### ISSUE TITLE
Add option to always show selectText

### ISSUE THREAD

**Issue by jhoobergs** [renrizzolo/react-native-sectioned-multi-select#23]
I think the behaviour with `selectText` is a bit strange / specific.
When one item is selected, the name of that item is shown, instead of the `selectText` and when multiple are selected, than it is a combination of `selectText`, the amount of selected and the names of the selected items. 

I would like the option to always show just the `selectText` independent of what is selected.

**Comment by renrizzolo** [comment]
@jhoobergs Sure, I will add `alwaysShowSelectText`.
This won't apply to single mode as the only way you can see what's selected in that mode is on the select label.

**Comment by renrizzolo** [comment]
This should be in v0.4.4, let me know if there are any problems

**Comment by pratik-gh** [comment]
`alwaysShowSelectText` not working in `0.7.6`  please check.

**Comment by renrizzolo** [comment]
I'm guessing this https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/33398ddb1ee62d607042031fd04c55603feba5bb/lib/sectioned-multi-select.js#L336-L338
needs to be moved further down to take precedence.

**Comment by pratik-gh** [comment]
> I'm guessing this
> 
> https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/33398ddb1ee62d607042031fd04c55603feba5bb/lib/sectioned-multi-select.js#L336-L338
> 
> 
> needs to be moved further down to take precedence.

I have placed at end but still it's not working also I have not used `single`

**Comment by renrizzolo** [comment]
This prop works as designed (even if that design is bad, hah). 
If you only select one item, it will show the `item[displayKey]`, if more than one item is selected, it will show the select text.
If the if clause mentioned above was moved down, the select text will show even with one item selected.
I can't debug your case without an example.

if you want to override the label, use ` renderSelectText`
```JS
 renderSelectText={() => 'select an item'}
```

**Comment by omair2010** [comment]
@renrizzolo you saved my life thank you
