### ISSUE TITLE
Add search keyword if item doesn't exist

### ISSUE THREAD

**Issue by huiming1313** [renrizzolo/react-native-sectioned-multi-select#24]
Hi,
Is there a way to add keywords if the given keyword can't be found from the item list.

For example when a user search specific item but no result found from the item list, there is a small add button to allow user to add and the modal will close.

After that the keyword will be added into the item list and a chip will be displayed for this keyword.

**Comment by renrizzolo** [comment]
Hi @huiming1313, this is not really in the scope of the library itself but you can do quite a bit by accessing the methods of the library through its ref.

To make this work nicely I've added a `searchAdornment` prop (available on the master branch) which takes a function returning the `searchTerm` (displayed on the right side of the text input). 
You can make that conditionally display your add button.

Here is a basic usage example (this assumes only adding parent items):

```JS
handleAddSearchTerm = () => {
  // returns the search input text
  const searchTerm = this.SectionedMultiSelect._getSearchTerm();
  // This will add a parent item
  const id = items[items.length - 1].id + 1;
  // check that the item doesn't exist
  if ( searchTerm.length && !items.some( item => item.title.includes(searchTerm) ) ) {
    const newItem = {id: id, title: searchTerm}; // user your uniqueKey / displayKey
    this.setState(prevState => {items: [...prevState.items, newItem]});
   // this will select the item and add it to the currently selected items
    this.onSelectedItemsChange([...this.state.selectedItems, id])
   // (optionally) close the modal
    this.SectionedMultiSelect._submitSelection()
  }
}

searchAdornment = (searchTerm) => {
  return(
  // only show if text has been input
    searchTerm.length ?
      <TouchableOpacity 
        style={{ alignItems: 'center', justifyContent: 'center'}} 
        onPress={this.handleAddSearchTerm}
      >
        <View>
          <Icon
            size={18}
            style={{ marginHorizontal: 15 }}
            name="add"
           />
        </View>
      </TouchableOpacity>
    : 
    null
  )
}

...

<SectionedMultiSelect
  items={this.state.items}
  ref={SectionedMultiSelect => this.SectionedMultiSelect = SectionedMultiSelect}
  uniqueKey="id"
  subKey="children"
  displayKey="title"
  searchAdornment={(searchTerm) => this.searchAdornment(searchTerm)}
  onSelectedItemsChange={this.onSelectedItemsChange}
  ...
/>
```

Let me know if this fulfils your needs.

**Comment by huiming1313** [comment]
Hi @renrizzolo 
Thanks for the reply, yes indeed this is what i wanted.  :)

**Comment by renrizzolo** [comment]
@huiming1313 cool, publishing on npm now.
