### ISSUE TITLE
TypeScript error when using ref

### ISSUE THREAD

**Issue by LeSerrurier** [renrizzolo/react-native-sectioned-multi-select#240]
**Hello here,**

I am having problems to use the library with TypeScript.

Firstly, the IconRenderer and icons parameters. I was the same issue than this [one ](https://github.com/renrizzolo/react-native-sectioned-multi-select/issues/229) . I solved it by modifying the library code as they advised. I dont know where the progress of the project is, but i would like to say it will be a good update to add this.

Secondly, i was in almost the same situation than this [issue](https://github.com/renrizzolo/react-native-sectioned-multi-select/issues/196) and i did exclaty as the owner advised [here](https://github.com/renrizzolo/react-native-sectioned-multi-select/issues/196#issuecomment-728693762). But, in my case in TypeScript i get an error.

![image](https://user-images.githubusercontent.com/65590507/123430555-9da5db00-d5c8-11eb-9736-00454c38d00d.png)

I tried to do that : 

![image](https://user-images.githubusercontent.com/65590507/123430864-f2495600-d5c8-11eb-9965-edcb070a322c.png)

And that :

![image](https://user-images.githubusercontent.com/65590507/123430715-c9c15c00-d5c8-11eb-8fa4-f2cfb3e54eec.png)

And tried to add Type for ref variable, but i did not succeed to pass this error. 
I dont know if it's me who doing it wrong, or if is the library who is not fit for TypeScript.

I would highly appreciate your support on this subject please !

**Comment by renrizzolo** [comment]
This should be fixed in `v0.8.2`, please re-open if it persists.

**Comment by LeSerrurier** [comment]
Thank you for advertising me !
About the first point, yes i no longer have the error, its perfect !

But, for the ref problem, i am in the same situation :
![image](https://user-images.githubusercontent.com/65590507/145970579-c853bda3-dd38-4002-8519-dccb1b704805.png)

Moreover, i saw a little mistake in the read.me, its not "_removeAllItems" but "_toggleSelector" :
![image](https://user-images.githubusercontent.com/65590507/145970882-f7f4d0f8-6e53-4306-b3a1-4af591a3d5a2.png)


And as you can see, i do the same than the example, but maybe its need to do differently in the new version ?

**Comment by renrizzolo** [comment]
working on it!

**Comment by renrizzolo** [comment]
@LeSerrurier can you try with latest master?
Also I converted the example to ts, maybe it will help with the ref stuff? https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/master/exampleapp/AppWithTypes.tsx

**Comment by LeSerrurier** [comment]
I have again the same error.
I wanted to follow your example, but there are a lot of errors in it, except when you use ref.
So I tried to get something and i get that :
![image](https://user-images.githubusercontent.com/65590507/145997000-2ba544ce-5468-4102-9f58-1ba9b6e61de1.png)

You used class component and you just declared "sectionedMultiSelectRef" as a private attribute. But you never give to it a value.
So i don't know what i am supposed to fill as value

**Comment by renrizzolo** [comment]
OK it's a bit different for a functional component.
You want to use `useRef` and pass the type in to that.

```jsx
import React, {useRef} from 'react';
import {View, Button} from 'react-native';
import SectionedMultiSelect from 'react-native-sectioned-multi-select';
import Icon from 'react-native-vector-icons/MaterialIcons';

type ItemType = {
  title: string;
  id: number;
};
const items = [
  {
    id: 1,
    title: 'Item 1',
  },
  {
    id: 2,
    title: 'Item 2',
  },
];

const App: React.FC = () => {
  const ref = useRef<SectionedMultiSelect<ItemType>>();
  const [selectedItems, setSelectedItems] = React.useState([]);

  const removeAll = () => {
    ref.current?._removeAllItems();
  };
  const toggle = () => {
    ref.current?._toggleSelector();
  };

  return (
    <View>
      <SectionedMultiSelect
        uniqueKey="id"
        displayKey="title"
        onSelectedItemsChange={setSelectedItems}
        selectedItems={selectedItems}
        items={items}
        ref={ref}
        IconRenderer={Icon}
      />
      <Button title="Open" onPress={toggle} />
      <Button title="Remove All" onPress={removeAll} />
    </View>
  );
};

export default App;
```

**Comment by LeSerrurier** [comment]
Oh ! Its working, I didnt get any error this time !
![image](https://user-images.githubusercontent.com/65590507/146012637-6a662c04-710b-4173-92ae-e888c8a35217.png)

But, that is just a part of isolated code, only here for test quickly.
I tried to change my "true" code, but i get some errors. I don't have time for see in more details. I have more urgent task in my company and i have a busy week.
I will try to continue to test another time, during this week i hope.

Thank you for your time and your help !  I'll keep you informed

**Comment by renrizzolo** [comment]
No problem!

**Comment by LeSerrurier** [comment]
Hello again, i tested more properly, and yes i still have problems. I think is about type.

In my app, i need to use several times your component. They are many arguments to give for use it, morever i want the same style everywhere, it will be a lot of copy paste. So, i created my own component. And with my component it's doesn't work : 
![image](https://user-images.githubusercontent.com/65590507/146734469-10451aba-92ec-428d-adac-c154f5599833.png)
![image](https://user-images.githubusercontent.com/65590507/146734826-cd303f49-bf9c-461b-9d91-5779ca065ff8.png)

It's doesn't display the select and inside there is no element.
In my MultiSelectModal i ask that props : 
```
type Props = {
    multiSelectModalRef: LegacyRef<SectionedMultiSelect<unknown>> | undefined,
    items: any | ServicesSortedType | ServicesSortedTypeDetailed | Goals, // i added any just for testing
    selectedItems: Array<string>,
    typeItems?: "services" | "goals"
    whiteText?: boolean,
    callbackAction: (newSelectedServices: Array<string>) => void,
}
```
So i tried to use the same type than your and it's doesn't work too : 
```
type Props = {
    multiSelectModalRef: ClassAttributes<unknown> | undefined,
    items: any | ServicesSortedType | ServicesSortedTypeDetailed | Goals,
    selectedItems: Array<string>,
    typeItems?: "services" | "goals"
    whiteText?: boolean,
    callbackAction: (newSelectedServices: Array<string>) => void,
}

interface ClassAttributes<T> extends Attributes {
    ref?: LegacyRef<T> | undefined;
}
interface Attributes {
    key?: Key | null | undefined;
}
type Key = string | number
```
Am I doing something wrong ?

**Comment by LeSerrurier** [comment]
I don't know how to remove stale label so i comment ^^' i have still my problem

**Comment by LeSerrurier** [comment]
Same thing

**Comment by renrizzolo** [comment]
Based on what I'm seeing in those type errors, ` LegacyRef<SectionedMultiSelect<unknown>>` needs to be changed to ` LegacyRef<SectionedMultiSelect<ItemType>>` where `ItemType` is the signature of your items `{id: number, title: string}`.

You might be able to just omit the item type on `SectionedMultiSelect`, I'm not sure.

**Comment by LeSerrurier** [comment]
Firstly, i replace my own types by ItemType to make it easier, i get this result : 
![base](https://user-images.githubusercontent.com/65590507/155085034-3ad746c8-6523-4449-8ec2-3ed6636f1625.PNG)

I get this following error on the ref :
![refError](https://user-images.githubusercontent.com/65590507/155085126-50b3400d-aa57-47f5-bf2a-e33c43481336.png)


Secondly, i tested yours advices, i started by omit the type on `SectionedMultiSelect` and i get this error : 
![OmitType](https://user-images.githubusercontent.com/65590507/155085887-477bfe30-5f0e-4fb7-a44e-2c9b37170538.png)

From what i understand, it's not possible to omit the type, it require one.
And if i add type on my `SectionedMultiSelect`, i get this : 
![image](https://user-images.githubusercontent.com/65590507/155086436-b9fb94f5-6b3f-42b6-b905-ed5acfd61cf2.png)

With this error on the component : 
![ComponentError](https://user-images.githubusercontent.com/65590507/155086505-02dbc441-bc01-4665-a87d-84d14ef052c0.png)

And i admit i don't understand it

**Comment by renrizzolo** [comment]
I'll have to look into it. I can fix the issue with requiring the item type but that's unrelated to the ref issue you're having.

Where is `multiselectModalRef` coming from? It looks like you've typed it as a legacy ref but you're expecting it to be a modern ref with the `current` property.

**Comment by LeSerrurier** [comment]
I ask it in the props because the component need a ref of that type :
![image](https://user-images.githubusercontent.com/65590507/155479688-4620576e-db9d-4922-9fa4-c090cdea927b.png)

But, in my previous screenshot, the `TouchableOpacity` was for testing yours first advices. Normally in my custom component i just return your component without using `current`. So, i had an oversight. Thanks for your help !

**Comment by renrizzolo** [comment]
The `ItemType` you pass to the multi select component is for the object, not an array of items.
you should take the array off the `ItemType` and change the prop's type to `items: ItemType[]`.
Then use it in your component:
```jsx
<SectionedMultiSelect<ItemType>
  // [props]
/>
```
I think something is wrong with your `Icon` type, it should be a react component.

I'm unsure of how your ref is defined, but unless your modal is a class it's probably `React.MutableRefObject<SectionedMultiSelect<ItemType>>`

**Comment by LeSerrurier** [comment]
Oooh !! It's seems to work ! Well, i need to wait next Monday to test correctly in my company, but i am really confident it's will works too !

For the `Icon`, i don't why i've had an error, but it disappeared.

It's seems to work with the `LegacyRef`, i keep you informed, thanks again !

**Comment by LeSerrurier** [comment]
Finally it's work ! I need to give an array of items and use a `LegacyRef<SectionedMultiSelect<TypeItemWithoutArray>>` (no need to `<SectionedMultiSelect<ItemType>...>`) and it's work. Thanks a lot for your help !

Now, i get a last error but i don't know if it's resolvable. In `onSelectedItemsChange`, the given `items` is the same type than the `items` given in component. But, it's no true, it returns the attribute selectionned in `uniqueKey`. 
![image](https://user-images.githubusercontent.com/65590507/155950940-71119d5a-ab95-40c4-bdb6-910508d3351a.png)

So, in this situation where `id` attribute is a number, for type correctly i need to do that  : 
`const _newItems = items as unknown as Array<number>`

It's not very annoying but it's not clean.
