### ISSUE TITLE
Can i change dropdown icon color without iconrenderer?

### ISSUE THREAD

**Issue by lvegh** [renrizzolo/react-native-sectioned-multi-select#246]
Hey!

Is there any way to changel the dropdown icon color from black to any other color without using iconrenderer ?
I am using the white layout and i managed to make the text the border color white but can't manage to change the dropdown icon color to white. Maybe i am missing something.

Many thanks!

**Comment by renrizzolo** [comment]
the icon is styled with `colors.selectToggleTextColor`. So you can either change that, or you can pass in your own component to `selectToggleIconComponent`.
