### ISSUE TITLE
[Question] How can I change the selected item icon color?

### ISSUE THREAD

**Issue by adamzolyak** [renrizzolo/react-native-sectioned-multi-select#250]
How can I change this check icon color from green to another color?
![Image 2021-10-27 at 12 30 12 PM](https://user-images.githubusercontent.com/5940516/139125443-214bf984-8b0f-4db3-84a5-a0631298802c.jpg)

I've been able to change the color of other icons by setting the `icon` prop to a custom object of icons, with the `check` icon's `color` prop set. This seems to work for all the other icons but not `check`. 
![Image 2021-10-27 at 12 30 46 PM](https://user-images.githubusercontent.com/5940516/139125521-c8c3e428-6065-446f-985e-413e0a7fa4dd.jpg)

Suggestions?

**Comment by renrizzolo** [comment]
it seems the icons have their colors applied via style.

this should work
```js
  check: {
    name: 'check-circle',
    style: {
      color: colors.secondary,
    },
    size: 22,
  },
```
