### ISSUE TITLE
Pre selected items not showing in model and chip

### ISSUE THREAD

**Issue by somagonda** [renrizzolo/react-native-sectioned-multi-select#257]
![d014131e-aac2-46c5-8bd7-adf8e9816b7d](https://user-images.githubusercontent.com/84760858/148194349-5b31dee0-a69e-451f-8a08-9de34af3c39a.jpg)

**Comment by somagonda** [comment]
@renrizzolo how to achieve this??

**Comment by renrizzolo** [comment]
Can you give some code or clarify what you expect to happen?
