### ISSUE TITLE
How to close modal after single item selection

### ISSUE THREAD

**Issue by TheNemus** [renrizzolo/react-native-sectioned-multi-select#261]
I'm struggling in order to find a way to close the modal after the user prompt its selection without using the "confirm" button.
It's possible?

I tried this:

```
function selectedItemsChangeHandler() {
    sectionedMultiSelect && sectionedMultiSelect.current && sectionedMultiSelect.current._toggleSelector();
}

<SectionedMultiSelect
          ref={sectionedMultiSelect}
          items={items}
          IconRenderer={Icon}
          uniqueKey="id"
          selectText="...."
          hideSearch={true}
          hideConfirm={true}
          single={true}
          onSelectedItemsChange={selectedItemsChangeHandler}
/>
```

but typescript says:
_Property '_toggleSelector' does not exist on type 'never'.ts(2339)_

**Comment by renrizzolo** [comment]
I believe this ts example works, and uses the `_toggleSelector` function 
https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/master/exampleapp/AppFunctional.tsx
