### ISSUE TITLE
Is there any way so as to get the id of the selected items' parent ?

### ISSUE THREAD

**Issue by sankcan55** [renrizzolo/react-native-sectioned-multi-select#262]
Like in the **Preview** if we select the item **Apple**, is there a way to know which section has been selected like in this case is **Fruit**?

**Comment by renrizzolo** [comment]
Not that I can recall. 
Depending on your items data, it shouldn't be too hard to match a selected item with a parent based on its ID. Or, add the parentId to each item and use `onSelectedItemObjectsChange` to get the whole object back.
