### ISSUE TITLE
How to use onSelectedItemObjectsChange ?

### ISSUE THREAD

**Issue by RalphSaridar369** [renrizzolo/react-native-sectioned-multi-select#263]
I tried to use it but I don't get anything in return. I do need this in order to differentiate between w categories

**Comment by renrizzolo** [comment]
If nothing is returned, you may not be selecting the items properly. 
You still need to call `onSelectedItemsChange`, set the selected items state, and pass that back to `selectedItems`.

**Comment by mrojas18** [comment]
i'm having the same problem....
