### ISSUE TITLE
Own search callback prop

### ISSUE THREAD

**Issue by Xyzor** [renrizzolo/react-native-sectioned-multi-select#27]
Hy!

I'd like to know if you're interested in this feature. If so, I could make a PR for it.

My plan is to add a new prop (eg.: findItem) as a callback function to be called instead of the built in find method.

```js
_findItem = (id) => {
    const { items, findItem } = this.props
    return findItem ? findItem(id, items) : this.find(id, items)
}
```

The reason I need this, is because I need accent-insensitive search for county list.

**Comment by renrizzolo** [comment]
@Xyzor The find method just returns the corresponding item to the provided id (uniqueKey) (and dives into the subKey to check there) I don't see how that relates to the item content (accents).
Do you mean to replace `_filterItems`?

**Comment by Xyzor** [comment]
Yes.

**Comment by renrizzolo** [comment]
@Xyzor I'm happy for you to add a PR for that
