### ISSUE TITLE
How to use **Styles** object and how can we open dropdowns by default when model opens

### ISSUE THREAD

**Issue by Zilleabbas10** [renrizzolo/react-native-sectioned-multi-select#28]
This is my select and styles object but it is not working...

```
 <SectionedMultiSelect
                      styles={{container: styles.container}}
                      colors={{primary: '#ef5350', text: '#ef5350', chipColor: '#ef5350'}}
                      items={items} 
                      uniqueKey='id'
                      subKey='children'
                      selectText='Type'
                      alwaysShowSelectText={true}
                      showDropDowns={true}
                      readOnlyHeadings={false}
                      selectChildren={true}
                      confirmText='Done'
                      onSelectedItemsChange={this.onSelectedItemsChange}
                      selectedItems={this.state.selectedItems}
                    />



const styles = StyleSheet.create({
  container: {
    backgroundColor: '#222', borderColor: '#CDCDCD', borderWidth: 1
  },
  chipContainer: {
    padding: 20,
    marginTop: 50
  }
});
```

**Comment by renrizzolo** [comment]
@Zilleabbas10 to open it you can use a ref
```js
<SectionedMultiSelect
  ref={ref => this.SectionedMultiSelect = ref}
/>

```

and the `_toggleSelector()` function will open/close it, so you can just fire it when your component has mounted:
 ```js
componentDidMount() {
  // programatically opening the select
  this.SectionedMultiSelect._toggleSelector();
}
```

As for the styles, how you're doing it works for me. Is it not styling it at all?

**Comment by Zilleabbas10** [comment]
>  this.SectionedMultiSelect._toggleSelector(); 
@renrizzolo  this line open modal programatically. but i want to open dropdowns by default that are used in this modal. 

And styles work for me now

**Comment by renrizzolo** [comment]
@Zilleabbas10 sorry, I misread the question.
Let me have a look, there's no way to do this at the moment.

**Comment by Zilleabbas10** [comment]
@renrizzolo No problem. I have figure it out by looking its documentation 
showDropDowns={false}
By adding this parameter DropDowns are shown by default.
But still there needs to be improvement that when Dropdowns are open by default, then there is no option fot closing any select if we want close any select. There should be option to close any select as we have option initially without using the parameter i mentioned above..

**Comment by renrizzolo** [comment]
> when Dropdowns are open by default, then there is no option fot closing any select if we want close any select.

@Zilleabbas10 Sorry I don't quite understand what you mean by this.

`showDropDowns={false}` will remove the ability to expand the dropdowns, so the sub items will always be shown.

Do you instead want the dropdowns to all be _expanded_ when `showDropDowns={true}`?

**Comment by Zilleabbas10** [comment]
yes i want to open select dropdowns by default when `showDropDowns={true}`

**Comment by thewithest** [comment]
Please can you let us know how you did for the container style ?
