### ISSUE TITLE
Expand dropdown function?

### ISSUE THREAD

**Issue by cyberdevnet** [renrizzolo/react-native-sectioned-multi-select#283]
Is there any way to detect the dropdown toggle when pressing the parent item?
I have the prop expandDropDowns set to false, I would like to detect when the dropdown is being opened and fire a callback.

THX :)

**Comment by renrizzolo** [comment]
Doesn't look like there's a callback for this. 
We could add something like:
```ts
onDropdownToggle(openState: bool, parentItemId: ItemId)
```
