### ISSUE TITLE
Checkmark is not visible when an item is selected

### ISSUE THREAD

**Issue by johnnydepup** [renrizzolo/react-native-sectioned-multi-select#295]
When I select an item from the list in the modal, I can see that the `onSelectedItemsChange` is being triggered in the background but the checkmark next to the item is not added. 

I don't see any config that could have disabled that. Here is my component and the configs. 

```
               <SectionedMultiSelect
                    items={habitsForModal}
                    ref={habitSelectorRef}
                    IconRenderer={Icon}
                    uniqueKey="id"
                    subKey="children"
                    selectText="Select habits to link"
                    hideSelect={true}
                    showDropDowns={false}
                    searchPlaceholderText='Search through existing habits'
                    onSelectedItemsChange={habitId => {
                        console.log(habitId);
                        console.log(selectedHabits);
                    }}
                    selectedItems={selectedHabits}
                />
```

Is there any extra config, I need? Right now, there is no visual feedback on the modal for the items that I have clicked on and selected.

**Comment by johnnydepup** [comment]
@renrizzolo, can you take a look at this? Am I missing something?

**Comment by johnnydepup** [comment]
Can we open this again? 
@renrizzolo , any comments on why this could be happening?

**Comment by KushalDesai1** [comment]
I am facing the same issue. Also, it is not allowing me to select multiple items from the list.

**Comment by renrizzolo** [comment]
My only guess is something to do with the icon not loading, or some css issue
