### ISSUE TITLE
How is selectedItems supposed to work?

### ISSUE THREAD

**Issue by johnnydepup** [renrizzolo/react-native-sectioned-multi-select#296]
How is the `selectedItems` key supposed to work? Would it store all the selected items from the list? It's not quite clear in the documentation. 

I am trying something like this:
```

    let selectedHabits = [];

              <SectionedMultiSelect
                    items={habitsForModal}
                    ref={habitSelectorRef}
                    IconRenderer={Icon}
                    uniqueKey="id"
                    subKey="children"
                    selectText="Select habits to link"
                    hideSelect={true}
                    showDropDowns={false}
                    searchPlaceholderText='Search through existing habits'
                    onSelectedItemsChange={habitId => {
                        console.log(habitId);
                    }}
                    selectedItems={selectedHabits}
                    onConfirm={() => console.log(selectedHabits)}
                />
```

I am printing the `selectedHabits` on clicking the confirm button, but it is always empty. I can get the selected items by setting them in the `onSelectedItemsChange` function. So, the need for `selectedItems` isn't quite clear.

Can you provide some details on how to use this?

**Comment by renrizzolo** [comment]
Think of it like a controlled input.
```jsx
<input type="text"   value={this.state.value}    onChange={this.handleChange} 
/>
```
In other words, `onSelectedItemsChange` must set (control) the `selectedItems` value
