### ISSUE TITLE
Add multiple display keys

### ISSUE THREAD

**Issue by SupriyaPKalghatgi** [renrizzolo/react-native-sectioned-multi-select#299]
@renrizzolo I want to include `count` with each `displayKey` item
Something like this
![image](https://github.com/renrizzolo/react-native-sectioned-multi-select/assets/95462949/7987a72c-25ec-4cb3-91a0-36a7bec967aa)

**Comment by SupriyaPKalghatgi** [comment]
@renrizzolo Can you please check this

**Comment by renrizzolo** [comment]
Hi, unfortunately this is not possible. 
You can override `dropDownToggleIconUpComponent`/`dropDownToggleIconDownComponent`, but you won't be able to determine which item it is.

**Comment by SupriyaPKalghatgi** [comment]
@renrizzolo I found many PRs open, could you please suggest which one out of them would be a good start for me to get this feature?
