### ISSUE TITLE
Anyway not to need so many icons?

### ISSUE THREAD

**Issue by ghost** [renrizzolo/react-native-sectioned-multi-select#30]
Anyway to make it to not need all of these icons. I have font awesome and that is enough for me but it won't run unless I also have MaterialIcons, etc.

**Comment by renrizzolo** [comment]
You can replace the icons with your own components, but unfortunately `react-native-vector-icons/MaterialIcons` must be imported for the default icons to work.

**Comment by eddietex** [comment]
Is there a workaround if I don't want icons at all to not install react-native-vector-icons? The other reason for this is that I'm using create-react-native-app, so I'm not able to use react-link and not willing to eject to ExpoKit only because of this library.

Thanks in advance!

**Comment by renrizzolo** [comment]
@esdrasevt hey, sorry there is no way that I'm aware of. You would need to fork or edit the package locally and remove all of the `react-native-vector-icons` import statements, and return something else for the icon components (there are props for all but the chip remove icon, which I will add in the next update).
