### ISSUE TITLE
Adding Accessibility Labels

### ISSUE THREAD

**Issue by tpravallika23** [renrizzolo/react-native-sectioned-multi-select#303]
Hi Team,

I am using React-native-sectioned-multi-select library in my app, all the functionality is good so far, however I can't find a way to add Accessibility labels to SectionedMultiSelect dropdown and subcategory drop-downs for my automation testing.
Please suggest.

Thank you.

**Comment by tpravallika23** [comment]
@renrizzolo Can you please help me with this

**Comment by renrizzolo** [comment]
Adding accessibility labels in #290 seemed redundant because they will be derived from the text of the touchable.
based on the text here: https://reactnative.dev/docs/accessibility#accessibilitylabel
> In the above example, the accessibilityLabel on the TouchableOpacity element would default to "Press me!". The label is constructed by concatenating all Text node children separated by spaces.

Is the issue that you need these explicitly set, or are you wanting to set a label that's different to the item text?

**Comment by tpravallika23** [comment]
> Adding accessibility labels in #290 seemed redundant because they will be derived from the text of the touchable. based on the text here: https://reactnative.dev/docs/accessibility#accessibilitylabel
> 
> > In the above example, the accessibilityLabel on the TouchableOpacity element would default to "Press me!". The label is constructed by concatenating all Text node children separated by spaces.
> 
> Is the issue that you need these explicitly set, or are you wanting to set a label that's different to the item text?
Thanks for your response @renrizzolo 
I am not able to find the elements in my automation code by the text of the touchable with the use of `AppiumBy.accessibilityId` in my code, is there any other identity locator I can use by giving the text of the touchable 
Note: I am not able to access both SelectText element as well as dropdown options
