### ISSUE TITLE
Display the component in a row along with other components

### ISSUE THREAD

**Issue by Bilal-Abdeen** [renrizzolo/react-native-sectioned-multi-select#306]
Thank you for the excellent library. 

I want to display the component in a row along with other components. Is this at all possible? 

Using style `style={{ flex: 1, flexDirection: "row", justifyContent: "flex-start", }}` (as you can see below) makes the component `SectionedMultiSelect` shrink to only the caret!
 
![Screenshot 2024-03-12 111613](https://github.com/renrizzolo/react-native-sectioned-multi-select/assets/8470766/8dd1eb5c-1106-4cab-8843-f880b04b4fe7)

It should be: 
![Screenshot 2024-03-12 113554](https://github.com/renrizzolo/react-native-sectioned-multi-select/assets/8470766/40e87262-f3ba-4a98-a5c9-b084d8c1df1e)

```javascript
<View style={{ flex: 1, flexDirection: "row", justifyContent: "flex-start", }}>
	<SectionedMultiSelect
		IconRenderer={Icon}
                styles={{ selectToggle: { maxWidth: 100 }}} 
		items={[ {value: "value 1"}, {value: "value 2"}, ]}
		uniqueKey="value"
		displayKey="value"

		single={true}
		readOnlyHeadings={false} 

		hideSearch={false}
		hideConfirm={true}
		hideSubmitButton={true}
		canAddItems={false}

		onSelectedItemsChange={ (value) => { props.acPhoneCountryCode(value[0]);  }}
		selectedItems={[props.phoneCountryCode]} 
		selectText="Country Code"
	/>
	<Text>Hello</Text>
</View>

```

**Comment by renrizzolo** [comment]
I'm not entirely sure, but looking at your markup it might be just a case of adding an extra wrapper around the select, that has some width or flex value. Or maybe adding `flexShrink: 0` or similar to `selectToggle` styles
