### ISSUE TITLE
Select toggle hidden

### ISSUE THREAD

**Issue by JinHoSo** [renrizzolo/react-native-sectioned-multi-select#34]
<img width="679" alt="2018-06-19 7 41 45" src="https://user-images.githubusercontent.com/31269303/41592812-d77083a6-73f8-11e8-86f8-4cf2b391acaf.png">

I can't see the select toggle button on iOS only, but Android is working well.
I think It seems like a flex issue. 
Let me fix and gonna PR for it.

**Comment by Pushpi1992** [comment]
At now, I can't see the select toggle button on iOS only, but Android is working well.
