### ISSUE TITLE
Missing selected value

### ISSUE THREAD

**Issue by michael-molina** [renrizzolo/react-native-sectioned-multi-select#36]
Missing selected value on iOS only. Working fine on android.

```
import React from 'react';
import { StyleSheet, View } from 'react-native';
import SectionedMultiSelect from 'react-native-sectioned-multi-select';

export default class App extends React.Component {

  constructor() {
    super();
    this.state = {
      selectedItems: [],
    }
  }

  onSelectedItemsChange = (selectedItems) => {
    this.setState({ selectedItems });
  }

  render() {
    const items = [
      {
        name: "Fruits",
        id: '0',
        children: [{
          name: "Apple",
          id: '10',
        }, {
          name: "Strawberry",
          id: '17',
        }, {
          name: "Pineapple",
          id: '13',
        }, {
          name: "Banana",
          id: '14',
        }, {
          name: "Watermelon",
          id: '15',
        }, {
          name: "Kiwi fruit",
          id: '16',
        }]
      }];

    return (
      <View style={styles.container}>
        <SectionedMultiSelect
            items={items}
            uniqueKey='id'
            subKey='children'
            showDropDowns={false}
            readOnlyHeadings={true}
            onSelectedItemsChange={this.onSelectedItemsChange}
            selectedItems={this.state.selectedItems}
            showChips={false}
            single={true}      
          />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```
![1](https://user-images.githubusercontent.com/40404971/41618943-ecd1f022-73da-11e8-8937-d3f710f206a1.JPG)![2jpg](https://user-images.githubusercontent.com/40404971/41618944-ecf5515c-73da-11e8-84d4-b5515b003487.JPG)

**Comment by renrizzolo** [comment]
@michael-molina Try changing `alignItems` to `stretch` and change `flex: 1` to `flexGrow: 1` in your container.

**Comment by michael-molina** [comment]
I already tried different layout changes, including the ones you mentioned, but nothing seems to work. This problem only happens on iOS. Android is working fine. The selected value only appears if a set selectToggle with a fixed width.

**Comment by michael-molina** [comment]
It worked with the fix provided in #34. Thank you and @JinHoSo for the fix.

**Comment by michael-molina** [comment]
I saw your comment on #34 rejecting @JinHoSo fix. But it only works if his suggestion is applied. Could  you try the code that I sent you and check if I'm doing something wrong? Thanks.

**Comment by renrizzolo** [comment]
@michael-molina I have tried various combinations, with/without flex and alignitems.
It seems only `alignItems: 'center'` will cause it to do that.
The view for the select has no width set on it, so it is aligning both children (text and icon) to the center.

This works for me:
```
 container: {
    flexGrow: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
}
```

If you're still having problems, you can apply your css via the styles prop, you don't need to edit the lib:
(I had no idea percentages were working in RN since 0.42!)
```
styles={{
  selectToggle: {
    width: '100%',
  },
}}
```
Another thing - if you can't see it at all I think it might be behind the notch on the X. Try adding a top margin to your container. 

Let me know how you go.

**Comment by michael-molina** [comment]
I discovered the reason for the error. One of my parent containers had a fixed height. Thank you so much for the support.

**Comment by michael-molina** [comment]
The problem was alignItems: 'center' as you mentioned. Thank you so much for the support.

**Comment by DenisDov** [comment]
You need to wrap SectionedMultiSelect in to ScrollView

**Comment by FrankyFrankFrank** [comment]
@DenisDov I fought using this solution for so long - turns out yours was the only one that worked consistently. Do you have any idea why?

**Comment by hmenzagh** [comment]
There is a related issue with `flex-end`
