### ISSUE TITLE
 Get item object instead of only id 

### ISSUE THREAD

**Issue by iCodePup** [renrizzolo/react-native-sectioned-multi-select#4]
Hello,

There is a way to get the full item object instead of only the key (like native Picker do) ?

Thanks.

**Comment by renrizzolo** [comment]
Hi, 
this isn't currently possible, do you have an example of why you'd need this over getting the object from your existing items with the key? It would be slight convenience but I don't think it's necessary.

**Comment by iCodePup** [comment]
Hi,

 I fetch my data from remote API with following sample structure :

`const items = [
  {  
    name: "Fruits",
    id: 0,
    children: [{
        name: "Apple",
        id: 10,
      },{
        name: "Strawberry",
        id: 17,
      },{
        name: "Pineapple",
        id: 13,
      },{
        name: "Banana",
        id: 14,
      },{
        name: "Watermelon",
        id: 15,
      },{
        name: "Kiwi fruit",
        id: 16,
      }]
  },
  {
    name: "Gems",
    id: 1,
    children: [{
        name: "Quartz",
        id: 20,
      },{
        name: "Zircon",
        id: 21,
      },{
        name: "Sapphire",
        id: 22,
      },{
        name: "Topaz",
        id: 23,
      }]
  },
  {
    name: "Plants",
    id: 2,
    children: [{
        name: "Mother In Law\'s Tongue",
        id: 30,
      },{
        name: "Yucca",
        id: 31,
      },{
        name: "Monsteria",
        id: 32,
      },{
        name: "Palm",
        id: 33,
      }]
  },
]`

Today if i select two elements, (Monsteria, Palm for example) i will have an selectedItems state array with two ID s

`[32,33].`

My need is to have an array with the full object with id 32 and 33 👍 

```
    [{
        name: "Monsteria",
        id: 32,
      },{
        name: "Palm",
        id: 33,
      }]
```
I don't want to make an other request to API to get the full object to build a new array 

Maybe i can filter on items and rebuild the object array but i can't find a good way to do this

**Comment by renrizzolo** [comment]
Hi @iCodePup, if you have a look at the dev branch I've added the prop `onSelectedItemObjectsChange`. This is a function that returns the objects. (The main onSelectedItemsChange function still needs to be present).

The only caveat is that the parent items' child items will be contained in that object (as you get the object back exactly as it is) even though they aren't selected. Although I think it's clear that the top level objects are the selected ones.

Let me know if this works for you.

**Comment by iCodePup** [comment]
Hey ! Thanks 👍 
It does the job but unfortunately onSelectedItemObjectsChange props seems to works for multiple select only .
It will be never call for single  :(

**Comment by renrizzolo** [comment]
@iCodePup thanks!
