### ISSUE TITLE
Limit select item

### ISSUE THREAD

**Issue by bolerap** [renrizzolo/react-native-sectioned-multi-select#40]
Hi all,
How can i limit selection item. for example i want user can only select 5 item.
Many thanks.

**Comment by renrizzolo** [comment]
@thanhngvpt you can do something like this in `onSelectedItemsChange`.
```js
const maxItems = 5
...
  onSelectedItemsChange = (selectedItems) => {
    if ( selectedItems.length > maxItems ) {
      return;
    }
    this.setState({confirmText:`${selectedItems.length}/${maxItems}`})
    this.setState({ selectedItems })
  }
```

You could also for examplehave it set a state flag and have that change the style to make the items greyed out.

**Comment by bolerap** [comment]
@renrizzolo  Many thanks. If it available in form props or config, will be great.

I've tried by change `itemText: {color: this.state.toggleSelectItemColor}` but this change color of all item. How can i make selected item has a color and not selected item has another color? (Sorry for reopen this issue)

**Comment by renrizzolo** [comment]
@thanhngvpt you should be able to do that in the latest version - there are separate keys for selected items and selected subitems: `selectedItemText`, `selectedSubItemText`. (You don't need your own selection logic, just use `itemText` for unselected and `selectedItemText` for selected).

I'm not sure about an item limit prop - the main problem is how to handle when all children are auto-selected (and it goes over the limit).

**Comment by bolerap** [comment]
@renrizzolo Ok, all good

**Comment by Kur0a5h** [comment]
How can you limit items selected while still allowing items to be deselected after the maxItems has been reached?
