### ISSUE TITLE
add keyboardShouldPersistTaps props

### ISSUE THREAD

**Issue by huiming1313** [renrizzolo/react-native-sectioned-multi-select#41]
currently if we search and select the item, we've to tap twice.
first tap to dismiss the keyboard,
second tap to select the items.

Possible to add this props so that users can search and select right away ?

I've try to add this props in `<modal>` and `<ScrollView>` inside the `<modal>` it worked well.

**Comment by renrizzolo** [comment]
Good catch. 
I have added it in the latest version - in my testing it was needed on the `scrollView` and the parent `FlatList`. 
You'd also need it on your own App's parent `ScrollView(s)` if any.
