### ISSUE TITLE
selectToggle disappear when color background is setted

### ISSUE THREAD

**Issue by camux** [renrizzolo/react-native-sectioned-multi-select#44]
When I put selectToggle: {backgroundColor: 'red'}
the selectToggle disappear, and just appear chips

<SectionedMultiSelect
            items={menuTags}
            uniqueKey='id'
            subKey='children'
            selectText={I18n.t('add_meals')}
            onSelectedItemsChange={this.onSelectedItemsChange}
            selectedItems={ selectedMenuTags }
            readOnlyHeadings={true}
            showDropDowns={true}
            expandDropDowns={true}
            showCancelButton={true}
            colors={{
              chipColor: color.greenDark,
              primary: selectedMenuTags.length? color.aqua : color.grayLight
            }}
            styles={{
              chipText: styles.chip_text,
              selectToggle: {backgroundColor: 'red'}
            }}
            onConfirm={this.handleSaveTags} />

**Comment by renrizzolo** [comment]
Hi, I'm not able to reproduce this. 
Are you on the latest version of `react-native-sectioned-multi-select`?

**Comment by ibraheeamm** [comment]
@renrizzolo yes I am on the last version and I am facing the same issue, I can not toggle the dropdown after it, After inspecting the application it appears that the view disappears

**Comment by eliasturbay** [comment]
Yes, it seems to be a regression. It's related to this issue:
https://github.com/renrizzolo/react-native-sectioned-multi-select/issues/34

And it was previously solved by this PR:
https://github.com/JinHoSo/react-native-sectioned-multi-select/pull/1
