### ISSUE TITLE
Wrong height on the list

### ISSUE THREAD

**Issue by peterwang88** [renrizzolo/react-native-sectioned-multi-select#45]
<img width="301" alt="screen shot 2018-07-18 at 4 20 47 pm" src="https://user-images.githubusercontent.com/25915931/42863473-acbf5d52-8aa6-11e8-9c4a-bcdcfd0eb25c.png">
<img width="297" alt="screen shot 2018-07-18 at 4 20 55 pm" src="https://user-images.githubusercontent.com/25915931/42863474-adc3e2fe-8aa6-11e8-80d7-c3ad6da2c990.png">

When expanded there is always extra padding or too much height on the rowItem?

**Comment by peterwang88** [comment]
I noticed when adding a view wrapper in the FlatList of RowItem.js will fix the issue, but not sure why. Has anyone encoutered this issue?

`
        { item[subKey] && this._showSubCategoryDropDown() &&
          <View>
            <FlatList
              keyExtractor={i => `${i[uniqueKey]}`}
              data={item[subKey]}
              extraData={selectedItems}
              ItemSeparatorComponent={this._renderSubSeparator}
              renderItem={this._renderSubItemFlatList}
            />
          </View>
        }
`

<img width="318" alt="screen shot 2018-07-18 at 4 28 37 pm" src="https://user-images.githubusercontent.com/25915931/42863892-f2dbcf86-8aa7-11e8-8851-5ec8dd9b23d1.png">

**Comment by renrizzolo** [comment]
Do you get the same result if you don't use an animation for the expanding? ( `animateDropDowns={false}`)
Does it only do it when you expand them (i.e not when `showDropDowns` is false)?
I've see the LayoutAnimation have some buggy height before.

**Comment by peterwang88** [comment]
Yes, it's still the same even after you set animateDropDowns={false}.

And it only happens when you expanding them.

**Comment by renrizzolo** [comment]
Hmm. I've tried on ios and android and I can't reproduce it.
Can you give me a full code example?

**Comment by peterwang88** [comment]
I have copied the exact code in the example, but it will still have the same issue.
I noticed it's because my react native version? Becuase I'm using a very old version on my project.

react-native-cli: 2.0.1
react-native: 0.46.4

but if I switch to the following version then it works fine.
react-native-cli: 2.0.1
react-native: 0.55.4

So the only workaround would be upgrade my react native version?

**Comment by renrizzolo** [comment]
I think that's likely the problem. It may be an underlying bug that was fixed somewhere between those versions.

Have you tried for example setting a fixed height on the items?

e.g `styles={{item: { height: 30 }, subItem: { height: 30 } }}`
