### ISSUE TITLE
fontFamily 'Material Icons' is not a system font and has not been loaded through Expo.Font.loadAsync

### ISSUE THREAD

**Issue by jamesangetonhouse** [renrizzolo/react-native-sectioned-multi-select#46]
Hi, I have adapted this library successfully previously but it started show an error like:
![the error screen capture](https://image.ibb.co/hujJtd/error1.png)

If dismiss the error, it show scissor (refer below)
![show a scissor icon](https://image.ibb.co/epxGeJ/error2.png)

**Comment by renrizzolo** [comment]
I'm not sure, this is related to Expo/elements which I don't use.
Couple issues here might give you a fix:
https://github.com/react-native-training/react-native-elements/issues/333
https://github.com/react-native-training/react-native-elements/issues/620

**Comment by brunokiafuka** [comment]
> Hi, I have adapted this library successfully previously but it started show an error like:
> ![the error screen capture](https://camo.githubusercontent.com/59e26b5a808fa55a27d634f47b583befe4e1990a/68747470733a2f2f696d6167652e6962622e636f2f68756a4a74642f6572726f72312e706e67)
> 
> If dismiss the error, it show scissor (refer below)
> ![show a scissor icon](https://camo.githubusercontent.com/1f81bbcdd88d05d313f1c6bc0a3f8fea2b663101/68747470733a2f2f696d6167652e6962622e636f2f65707847654a2f6572726f72322e706e67)

You have to load font, https://stackoverflow.com/questions/49311395/react-native-expo-font-loadasync-doesnt-load-material-icons

**Comment by Bound3R** [comment]
:thinking: Hello I had the same problem using expo.

To fix it, I did this:
```javascript
import { MaterialIcons } from '@expo/vector-icons'
```
and

```javascript
<SectionedMultiSelect
  ... configs ...
  selectToggleIconComponent={<MaterialIcons name="keyboard-arrow-down" size={24} />}
  searchIconComponent={<MaterialIcons name="search" size={24} />}
  selectedIconComponent={<MaterialIcons name="check" size={24} />}
  dropDownToggleIconUpComponent={<MaterialIcons name="keyboard-arrow-up" size={24} />}
  dropDownToggleIconDownComponent={<MaterialIcons name="keyboard-arrow-down" size={24} />}
  cancelIconComponent={<MaterialIcons name="cancel" size={24} />}
  chipRemoveIconComponent={<MaterialIcons name="close" size={24} />}
/>
```

**Comment by renrizzolo** [comment]
I'm looking at a way to conditionally import RN vector icons, so you could use your own icon component instead.
