### ISSUE TITLE
callback function when modal is open or close

### ISSUE THREAD

**Issue by huiming1313** [renrizzolo/react-native-sectioned-multi-select#48]
Is there a way to trigger a function when the modal is open or close ?
I need to programmatically update the keyboardShouldPersistTaps state for my parent ScrollView. It's because in my ScrollView I've other input, if I set my ScrollView keyboardShouldPersistTaps to "always" we won't be able to dismiss the keyboard when we tap on the screen.

**Comment by renrizzolo** [comment]
Not from memory. I'll have a look and add it.

**Comment by renrizzolo** [comment]
Added in upcoming version
