### ISSUE TITLE
peer dep missing

### ISSUE THREAD

**Issue by YoucefMami** [renrizzolo/react-native-sectioned-multi-select#5]
Hi, when using your package, I get the below errors:
npm ERR! peer dep missing: react@16.0.0-alpha.6, required by react-native-sectioned-multi-select@0.2.0
npm ERR! peer dep missing: react-native@^0.44.0, required by react-native-sectioned-multi-select@0.2.0

Should I downgrade my version of react-native to be able to use your package? Is there a reason why you have a dependency on react and react native in your package.json?

Thank you

**Comment by renrizzolo** [comment]
Good question- as far as I can tell this is not needed. (This was initally forked from https://github.com/toystars/react-native-multiple-select which has these peer dependencies).
My understanding is it's to denote the minimum required version and is a harmless warning.

I will take a look and probably remove them.

**Comment by YoucefMami** [comment]
Thanks for looking into it
