### ISSUE TITLE
Default style isnt from gif examples?

### ISSUE THREAD

**Issue by jstansbe** [renrizzolo/react-native-sectioned-multi-select#51]
I like the styles for this component as shown in the gifs... but they aren't the default! 
Awesome component -- performance and customization is great. 🥇

**Comment by renrizzolo** [comment]
You're not wrong! All i can say is some of the default styles and colours evolved throughout development.

This should get you pretty close though:
```
styles={{
  selectToggle: {
    backgroundColor: '#ececec',
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  confirmText: {
    color: '#2e2e2e'
  },
  searchBar: {
    backgroundColor: '#ffffff',
  }
}}
colors={{ primary: '#ececec', }}
searchTextFontFamily={{fontFamily: Platform.OS === 'android' ? 'bold' : 'Avenir', fontWeight: 'bold' }}
```

Thanks!
