### ISSUE TITLE
Empty Array

### ISSUE THREAD

**Issue by pedrobertao** [renrizzolo/react-native-sectioned-multi-select#52]
Empty Arrays leads to infinity loading component. This needs to have some props to handle "No data available".

**Comment by renrizzolo** [comment]
The loading component is rendered when items is an empty array, so there's no recognized 'empty' state.

You could do something like in the example. Assuming you have some kind of fetch function to get the items, just let the loading component know if it is empty.

```
  fetchItems = () => {
    this.setState({ hasErrored: false })
    fetch(url)
      .then(response => response.json())
      .then((responseJson) => {
        if (!responseJson.length) {
          this.setState({ noItems: true })
        } else {
          this.setState({ items: responseJson })
        }
      })
      .catch((error) => {
        this.setState({ hasErrored: true })
        throw error.message
      })
  }
```

```
const Loading = props => (
    props.noItems ? <Text> no items... </Text>
     :
    <View style={styles.center}>
      <ActivityIndicator size="large" />
    </View>
)
```

Another alternative is to push `{title: 'No Items', disabled: true}` to items when it's empty.

To add a `noItems` component we'd have to defer loading to when items is null/undefined, and make `noItems` display when the array is empty. So it would change the behaviour of the component a little bit. I think I'm ok with it though.

**Comment by pedrobertao** [comment]
Nice. Will try to have something like that. 
Thanks for the response.

**Comment by matias91** [comment]
First of all, thanks for the great work. This component was exactly what i needed.

I have the same problem.
My use case: I have two selects and the values of second one depends on the selected value of the first one.

Your workaround works in my case, @renrizzolo.
It would be great that the default behaviour was an empty message, and have a `loading` prop that the user can set, if needed.

Thanks!

**Comment by renrizzolo** [comment]
@pedrobertao @matias91 If you guys could have a look at the master branch and see if that works for you that would be great, then I'll publish it.

### Instead of showing the loading component when items are empty: 
- `loadingComponent` is shown when `loading` prop is true
- `noItemsComponent` is shown when there are no items (and search is empty)
- `noResultsComponent` is show when filtering items and there are no results

Just want to make sure it works for your use cases.
