### ISSUE TITLE
App is crashing in release mode

### ISSUE THREAD

**Issue by mustafadinler** [renrizzolo/react-native-sectioned-multi-select#53]
App is crashing in release mode while click item. And its said
**"TypeError: undefined is not a function (evaluating '_iterator[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()') This error is located at: in VirtualizedList (at FlatList.js:644) in FlatList (at sectioned-multi-select.js:812)"**
Evething is ok on debug mode. Probably about  
**newItems = [...selectedItems, item[uniqueKey]];** 
line but not sure.

**Comment by renrizzolo** [comment]
Hmmm, sorry I have no idea what the cause is.
It's referring to `Symbol` which this lib doesn't use (at least not
directly)

Is this on android only?

You could try https://github.com/react-community/jsc-android-buildscripts

**Comment by mustafadinler** [comment]
Yeah i tried that only on android emulator and android phone.

**Comment by renrizzolo** [comment]
I have tried a release build on android, I couldn't replicate the crash you got. 
It did crash in another case - trying to use the search filter when there are no items, so I'll patch that.

What version of RN are you using?

another fix mentioned here might work https://github.com/facebook/immutable-js/issues/1305#issuecomment-341308925

**Comment by mustafadinler** [comment]
I tried your first solution about jsc android buildscripts and errors gone, worked well. But i dont know why it is worked? :) thanks for your fast helps.

**Comment by renrizzolo** [comment]
From what I read the android Javascript engine that react native builds with is old and doesn't support various features that the debug engine (chrome) does. 
It's pretty weird and I'll have to look out for it in future!
