### ISSUE TITLE
Reload Application does not close Modal

### ISSUE THREAD

**Issue by zigzactly** [renrizzolo/react-native-sectioned-multi-select#54]
Seems like reloading of the app either in emulator mode or actual device does not close the modal. This occurs if the modal was already open prior to reloading app. The modal then becomes unresponsive and cannot be interacted with. 

Anyone else having this problem?

**Comment by zigzactly** [comment]
Just realized its an ongoing upstream issue: https://github.com/facebook/react-native/issues/17986

**Comment by renrizzolo** [comment]
Yeah, not sure about this, it seemed to happen intermittently when I tried to repro it.
It's a development only issue right?

**Comment by zigzactly** [comment]
Yes seems like only a dev problem at least for me.
