### ISSUE TITLE
Issue: All 'children' Items are not appearing in the screen,  when i tap on 1 item then rendering remaining item in the screen.How can i fix to render all the item in the screen.

### ISSUE THREAD

**Issue by harishbelamkar** [renrizzolo/react-native-sectioned-multi-select#55]
![simulator screen shot - iphone 6 - 2018-09-20 at 11 02 50](https://user-images.githubusercontent.com/34793541/45801382-d4868e00-bcc4-11e8-967b-307860f6f729.png)

**Comment by renrizzolo** [comment]
Hi, I'm not able to reproduce this, can you give me some code to try?
It may have something to do with the `<FlatList/>` props `removeClippedSubviews` /  `initialNumToRender={15}`? Or the `shouldComponentUpdate` methods.

**Comment by saifkamaal** [comment]
The issue is resolved if we add  initialNumToRender={200} to  <FlatList> in RowItem.js.

Example

`<FlatList
            initialNumToRender={200}
            keyExtractor={i => `${i[uniqueKey]}`}
            data={item[subKey]}
            extraData={selectedItems}
            ItemSeparatorComponent={this._renderSubSeparator}
            renderItem={this._renderSubItemFlatList}
          />`

I guess we need to add one more prop for rendering the nos of childer in the parent component.

**Comment by ironworkshop** [comment]
Thanks @saifkamaal this solved my issue!!!!
