### ISSUE TITLE
Crash when clicking on items in subcategory

### ISSUE THREAD

**Issue by Ares513** [renrizzolo/react-native-sectioned-multi-select#58]
On Android, when I click on anything in the menu, I get this:
`TypeError: TypeError: undefined is not a function (evaluating '_iterator[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')`

Tried this fix as suggested elsewhere, didn't fix it:
```
import MultiSelect from 'react-native-multiple-select';
import 'core-js/es6/map'
import 'core-js/es6/symbol'
import 'core-js/fn/symbol/iterator'
```

I'm just using the example with no changes and getting this problem.

**Comment by mustafadinler** [comment]
If it crashes on release mode;
You could try https://github.com/react-community/jsc-android-buildscripts
that works fine for me.
