### ISSUE TITLE
selectedItemText Dont Work

### ISSUE THREAD

**Issue by ruballos** [renrizzolo/react-native-sectioned-multi-select#59]
Another styles work fine, but this dont work:

styles={{selectedItemText:{color:'red'}, another... }}

Help!

**Comment by renrizzolo** [comment]
I can't see any reason why this wouldn't work.
Don't forget you need to use `selectedSubItemText` for the child items.

**Comment by ruballos** [comment]
`  <SectionedMultiSelect
                        selectText={this.state.texto_tipopropiedad}
                        confirmText='Listo'
                        searchPlaceholderText='Buscar'
                        noResultsComponent='Sin resultados'
                        items={this.state.tipo_propiedad}
                        uniqueKey='id'
                        single={false}
                        showChips={false}
                        selectedText={'checks'}
                        selectedItems={this.state.selectedItems_tipo}
                        onSelectedItemObjectsChange={(seleccion)=>{
                        }}
                        onSelectedItemsChange={(seleccion)=>{
                        }}
                        styles={{selectedSubItemText:{color:'red'}, itemText:{marginLeft:10}, selectedItem:{color:'blue', backgroundColor:'#DADADA', borderRadius:15, marginVertical:1}, confirmText:{color:'#4D5656'}, selectToggleText: {color:'white', fontSize:12, textAlign:'center'}, button:{backgroundColor:'#F7DC6F'} }}`


Dont Work :(

**Comment by ruballos** [comment]
Dont Work :(

`<SectionedMultiSelect selectText={this.state.texto_tipopropiedad} confirmText='Listo' searchPlaceholderText='Buscar' noResultsComponent='Sin resultados' items={this.state.tipo_propiedad} uniqueKey='id' single={false} showChips={false} selectedText={'checks'} selectedItems={this.state.selectedItems_tipo} onSelectedItemObjectsChange={(seleccion)=>{ }} onSelectedItemsChange={(seleccion)=>{ }} styles={{selectedSubItemText:{color:'red'}, itemText:{marginLeft:10}, selectedItem:{color:'blue', backgroundColor:'#DADADA', borderRadius:15, marginVertical:1}, confirmText:{color:'#4D5656'}, selectToggleText: {color:'white', fontSize:12, textAlign:'center'}, button:{backgroundColor:'#F7DC6F'} }}
`

**Comment by ruballos** [comment]
Dont Work :(

`<SectionedMultiSelect selectText={this.state.texto_tipopropiedad} confirmText='Listo' searchPlaceholderText='Buscar' noResultsComponent='Sin resultados' items={this.state.tipo_propiedad} uniqueKey='id' single={false} showChips={false} selectedText={'checks'} selectedItems={this.state.selectedItems_tipo} onSelectedItemObjectsChange={(seleccion)=>{ }} onSelectedItemsChange={(seleccion)=>{ }} styles={{selectedSubItemText:{color:'red'}, itemText:{marginLeft:10}, selectedItem:{color:'blue', backgroundColor:'#DADADA', borderRadius:15, marginVertical:1}, confirmText:{color:'#4D5656'}, selectToggleText: {color:'white', fontSize:12, textAlign:'center'}, button:{backgroundColor:'#F7DC6F'} }}

`

**Comment by renrizzolo** [comment]
Nothing will happen if you don't update your selected items state

`onSelectedItemsChange={(seleccion) => this.setState(selectedItems_tipo: seleccion)}`

**Comment by Vivekchudasma** [comment]
Hi @renrizzolo,

> I'm not able to selectedItems. Please check the below image.

> Multi selection not working. 


![image](https://user-images.githubusercontent.com/24473813/102625786-04ef5800-416c-11eb-9957-9a22078abbdb.png)

**Comment by renrizzolo** [comment]
@VivekkChudasama is `selectedItems` coming from your state? and what is `this.onSelectedItemsChange`?
`onSelectedItemsChange` should set the value of the `selectedItems` state.
So your `onSelectedItemsChange` function should look something like this:
```js
onSelectedItemsChange = (selectedItems) => this.setState({selectedItems})
```
