### ISSUE TITLE
How to change the style of the actual main component?

### ISSUE THREAD

**Issue by KosGrillis** [renrizzolo/react-native-sectioned-multi-select#60]
I'd like to change the style of the main component. i.e. the component that the user taps to open the multi select modal. Is this possible? If so, how?

**Comment by renrizzolo** [comment]
That is `selectToggle` (the View) and `selectToggleText` (the Text) in the styles prop.
and `selectToggleIconComponent` if you want to replace the Icon with your own component.

**Comment by IndianAg0711** [comment]
@renrizzolo Should it be possible to override the styles of the selectToggle component? I'm passing through a style object of `style={{ selectToggle: { padding: 0 } }}` but it doesn't seem to affect the rendering.

**Comment by KosGrillis** [comment]
@IndianAg0711 Could this be a simple typo? You need to pass your styles into the `styles` prop of sectioned multi select, rather than `style` prop which is default React.

**Comment by IndianAg0711** [comment]
Bah! That was it. Cheers for the oversight @KosGrillis!

**Comment by viv3kk** [comment]
how do I change container bottom margin from 15 to x 
`styles={{container:{marginBottom:0}}}`

**Comment by hgezim** [comment]
I'm still unclear on how to override the rendering of the `selectToggle` (name not obvious at all, BTW).

I'd like to just render a button instead of text but still want the little pill buttons that show what got selected.

**Comment by hgezim** [comment]
I've come close to making the toggle select a single button with these props:

```
styles={{
            selectToggle: {
              backgroundColor: '#8BC540',
              alignItems: 'center',
              alignContent: 'center',
              height: 50,
              marginBottom: 12,
            },
          }}
        renderSelectText={() => {
          return (
            <Text
              style={{
                paddingBottom: 13,
                paddingTop: 13,
                color: '#F5F4F4',
                shadowColor: '#00000029',
                shadowOffset: {
                  height: 3,
                  width: 0,
                },
                shadowOpacity: 1,
                shadowRadius: 6,
                fontSize: 20,
              }}
            >
              Filters
            </Text>
          );
        }}
        selectToggleIconComponent={<Text></Text>} // needed to remove icon on Filter component
        
```
![IMG_5813](https://user-images.githubusercontent.com/124675/69917928-e4e9db00-1428-11ea-895d-2eadf00f2d5b.jpg)

However, I can't seem to center the button's text. Ideas?

**Comment by renrizzolo** [comment]
Hmm, I see what you want to do. What if you just use the `hideSelect` prop and create your own button component?
`<SectionedMultiSelect>` would just render the chips in this case.
You'd have to add the `_toggleSelector()` onPress method  yourself (using a ref).

Have you tried `textAlign: 'center'` on your text element? and / or `flex: 1` on the `selectToggle`.
