### ISSUE TITLE
Regular expression error while searching

### ISSUE THREAD

**Issue by ghost** [renrizzolo/react-native-sectioned-multi-select#64]
I am using the list with search where user will be inputting country codes for phone number. Country codes bring with + and hence if user searches for +91 it throws an error as shown in the image below.

![photo_2018-10-18_17-39-41](https://user-images.githubusercontent.com/37217713/47153307-d875f200-d2fc-11e8-9ff5-4ef03595e42c.jpg)

**Comment by renrizzolo** [comment]
Hi, thanks for picking this error up.
I'll fix this, but you may prefer to provide your own filtering function with `filterItems` prop.
