### ISSUE TITLE
SafeAreaView not considered

### ISSUE THREAD

**Issue by tomacotuna** [renrizzolo/react-native-sectioned-multi-select#66]
Hey, firstly i love this component it is exactly what I was looking for, so thank you for saving me so much time.

I found a small issue when using it tho, as I develop my application for an iPhone X(since its my testing device) I noticed that the "notch" is a bit overlaying the search modal. I checked the code and around the line 870, you have a View component where you manually set some margins.

If you could change this line:
          ```<View style={[{ flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' }, styles.backdrop]}>```
To: 
         ```<SafeAreaView style={[{ flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' }, styles.backdrop]}>```

SafeAreaView is a components offered by React Native that deals with things such as the notch. You could make it as a props perhaps if you dont want it to always be used. (modalWithSafeAreaView: boolean)
Without SafeAreaView:

![screenshot 2018-10-25 at 13 49 09](https://user-images.githubusercontent.com/22911685/47501200-c6480680-d85c-11e8-85eb-2dbbb171fa0f.png)

With SafeAreaView:
![screenshot 2018-10-25 at 13 53 52](https://user-images.githubusercontent.com/22911685/47501446-76b60a80-d85d-11e8-8b2f-c6be1ead7e19.png)

**Comment by renrizzolo** [comment]
It looks as though this doesn't work properly on iOS 10 & below (https://github.com/facebook/react-native/issues/17638) – so I'm not sure if it should be the default.

I'm happy to add the prop for it for now

**Comment by tomacotuna** [comment]
Uhhh i see, i think having it as a prop would be the best in that case
