### ISSUE TITLE
Select Toggle Text is not coming up

### ISSUE THREAD

**Issue by thlee1122** [renrizzolo/react-native-sectioned-multi-select#68]
Hello,

Select Toggle Text is not coming up for me.
I have used `selectToggleText` to style it but that still does not fix my issue.

Here is my code:
`<View>
                  <SectionedMultiSelect
                    hideTags
                    style={{borderWidth: 1, borderColor: 'black', backgroundColor: 'blue', zIndex: 10}}
                    items={items} 
                    uniqueKey='id'
                    subKey='children'
                    selectText='Choose some things...'
                    showDropDowns={true}
                    readOnlyHeadings={true}
                    ref={(component) => { this.multiSelect = component }}
                    onSelectedItemsChange={this.onSelectedItemsChange}
                    selectedItems={this.state.selectedItems}
                    tagRemoveIconColor="#CCC"
                    tagBorderColor="#CCC"
                    tagTextColor="#CCC"
                    selectedItemTextColor="#CCC"
                    selectedItemIconColor="#CCC"
                    itemTextColor="#000"
                    displayKey="name"
                    searchInputStyle={{ color: '#CCC' }}
                    submitButtonColor="#CCC"
                    submitButtonText="Submit"
                    styles={{
                      backdrop: {
                        justifyContent: 'center',
                      },
                      container: {
                        width: '80%',
                        height: '80%',
                        flex: 0,
                        alignSelf: 'center',
                      },

                      selectToggle: {
                        backgroundColor: 'blue',
                        borderWidth: 1,
                        borderColor: 'black',
                        padding: 20,
                        height: 100,
                        marginTop: 8,
                        width: 320,
                        alignItems: 'center', 
                        alignSelf: 'center', 
                      },

                      selectToggleText: {
                        color: 'white',
                        zIndex: 10
                      }
                    }}
                  />
                </View>`

Here is the screenshot of my app.
The blue box is the `select toggle` and `select toggle text` should appear in there but it doesn't seem to work.
Could anyone please help me with this?

![image](https://user-images.githubusercontent.com/18387214/47690238-ab122980-dbc3-11e8-8e60-1cf26e0f7d0d.png)

**Comment by renrizzolo** [comment]
I tried with your code and the text shows for me in white.

Can you try using the inspector where the text should be? This will tell you which styles are applied to the Text component. It may be something to do with the styles on the outer container of the component.

FYI none of those color props you're using are part of this component.
colors is an object (like styles).
```
colors={{
  primary: '#3f51b5',
  success: '#4caf50',
  cancel: '#1A1A1A',
  text: '#2e2e2e',
  subText: '#848787',
  selectToggleTextColor: '#333',
  searchPlaceholderTextColor: '#999',
  searchSelectionColor: 'rgba(0,0,0,0.2)',
  chipColor: '#848787',
  itemBackground: '#fff',
  subItemBackground: '#ffffff',
  disabled: '#d7d7d7',
}}
```

**Comment by thlee1122** [comment]
@renrizzolo Hello Thank you for your reply.
I found out why it was not showing up.
I had to put `height` to `selectToggleText`.
I need to do the same thing for the "select Toggle Icon", the arrow icon.
How can I style this?

**Comment by renrizzolo** [comment]
I'm not sure why you'd need to put height on it...
Can you try with `flex :1` on the `selectToggle` (maybe it's being overridden) ?

you can't style the icon but you can replace it with your own component with `selectToggleIconComponent`

**Comment by thlee1122** [comment]
@renrizzolo 
Thank you for your reply.
I figured out why that was happening.
As you know, when you select items in the list, it would create a chip for each one.
Is there a way to style the "container", which contains all the chips and is placed below the "SelectToggle"?

**Comment by renrizzolo** [comment]
I'll add the `chipsWrapper` style key.
You can also use `customChipsRenderer` to build the chips yourself.

**Comment by Cadrach** [comment]
> @renrizzolo
> Thank you for your reply.
> I figured out why that was happening.

Could you tell me how you fixed it? I have the same behavior on my side... Thanks!
