### ISSUE TITLE
customChipsRenderer doesn't work.

### ISSUE THREAD

**Issue by apsuva** [renrizzolo/react-native-sectioned-multi-select#69]
Hi

The customChipsRenderer is causing high cpu usage and does not work. When I activate customChipsRenderer, my macbook pro starts to warm up. You can check my package.json

{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-sectioned-multi-select": "^0.6.1",
    "react-native-vector-icons": "^6.0.2"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "babel-preset-react-native": "4.0.1",
    "jest": "23.6.0",
    "react-test-renderer": "16.3.1",
    "reactotron-react-native": "^2.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by renrizzolo** [comment]
I'll take a look

**Comment by renrizzolo** [comment]
I have narrowed it down to the chips renderer function returning components in the props (e.g `loadingComponent`.)
I am going to change it to only return:
```
  uniqueKey,
  subKey,
  displayKey,
  items,
  selectedItems,
  colors,
  styles,
```
