### ISSUE TITLE
Checkmark hidden 

### ISSUE THREAD

**Issue by iCodePup** [renrizzolo/react-native-sectioned-multi-select#7]
Hello,
With multiselect , if the text label is too long (or display several lines) the checkmark is hidden.

Thanks

**Comment by renrizzolo** [comment]
@iCodePup thanks for letting me know, looks like that's an easy fix.
On that topic, what do you think about truncating long labels with `numberOfLines`?

I'm thinking either the number of lines is a prop (so it will always be truncated with ellipses past x lines), or it could be set to 1 line when the item is selected. (So you can read the whole label initially)

**Comment by iCodePup** [comment]
@renrizollo you re welcome, thanks for your work .
 In my opinion, your first solution by adding 'numberOfLines' props should be great .
I think its necessary to let the avaibility to choose between whole label display (over and above selected status) and truncated.
