### ISSUE TITLE
Feature Request: Header / Title,  Position Search Bar,  Component support (<Header>, <Text>)

### ISSUE THREAD

**Issue by ericchen0121** [renrizzolo/react-native-sectioned-multi-select#70]
I really like your multiselect component and the work you've done  on it. 

In implementing it, I'd really like to customize it, in order to add a component within the modal, above or below it, for example, a block of informational text or a <Header> component, or app icon, for example. 

I'd like to add a title to the modal, or a question, such as "What are you looking for?", currently, I only have one list and so the "name" key in the list is what I use for this title/question. 

-Title / Header text ABOVE the search bar
-positioning the search bar, above or below this Title

Thanks for your work on this!

**Comment by renrizzolo** [comment]
Hi, have you tried `headerComponent` prop? This allows you to add a component above the search bar.
