### ISSUE TITLE
Performance issue with long items list (~700 items)

### ISSUE THREAD

**Issue by eliasturbay** [renrizzolo/react-native-sectioned-multi-select#71]
Hi @renrizzolo 

As you can see in the attached gif, there’s a performance issue in the library when we have a long list. I initially thought it had to do with the `find` method but I implemented a binary search just to check if it improves, but it was the same. So I’m not quite sure what the problem is. 
Cloud you please take a look? It only happens the first time you tap on a subitem. But then if you close the modal and re open it again it happens again upon the first tap on a subitem

![a757a5bb-8814-4d2e-83e5-a0e0f384dea6](https://user-images.githubusercontent.com/314122/48295925-834a7d80-e46f-11e8-8b23-b8518a5def58.gif)

**Comment by renrizzolo** [comment]
I have spent some time trying to get the FlatList to perform well with large lists, but having trouble with either unnecessary re-rendering or it just takes a long time to render all the items, which is probably causing the slowdown in your case. (try scrolling down the list until everything has rendered and see if the first press is still slow?)

Unless you are doing some style/color change when the first item is pressed, I can't see why this wouldn't perform at least 'ok' though..

Can you try changing `RowSubItem.js` line 10 to 
`class RowSubItem extends PureComponent {`
(you'll also need to import `PureComponent` and remove the `shouldComponentUpdate` function).

Actually I think that might be worse in your case. I've noticed the above improves performance if there's a lot of parent items with a few children each.

**Comment by eliasturbay** [comment]
@renrizzolo I’m not in front of my computer right now. But I just tried to do what you suggested about scrolling down thru the whole list until everything is loaded. But that seems to be the real problem... actually it doesn’t render/populates the whole list (the last item in the list starts with “C”, and we have a lot more). And those that are missing are being loaded once you tap in any subitem to select it. That’s what is causing the performance issue. Then when the list is fully loaded, toggling an item doesn’t take too much time.
Tomorrow I’ll try to dig in trying to find the cause of that issue. But any clue or suggestion you might have will be welcome. 
Thanks!

**Comment by renrizzolo** [comment]
Hmm. Not too sure.
I found that making the `RowSubItem` a `PureComponent` allowed you to interact with the list while it's still loading, but had performance setbacks in general because it's re-rendering every sub item on every interaction.

There are a few performance related props for `FlatList`, this component uses `removeClippedSubviews`, `initialNumToRender` and `extraData`.
Maybe have a look at the docs on these? https://facebook.github.io/react-native/docs/flatlist

There are a lot of issues re: flatlist rendering/performance e.g https://github.com/facebook/react-native/issues/13316

**Comment by Bilal-Abdeen** [comment]
@renrizzolo 
Thank you for the excellent library. I have the same issue with a long list of options (more than 1.2K). I understand there might be little to do about it. 

However, I would like to suggest the capability to display an activity indicator (spinner) as soon as the dropdown list is displayed, and hidden as soon as the complete list of options is loaded. It would be great to pass a component for use as the activity indicator.
