### ISSUE TITLE
No children or subkey, however when select parent, there are no check mark indicator

### ISSUE THREAD

**Issue by duymnguyen9** [renrizzolo/react-native-sectioned-multi-select#74]
I modifed your example Items to:
`const items = [{
        name: "Apple",
        id: 10,
      },{
        name: "Strawberry",
        id: 17,
      },{
        name: "Pineapple",
        id: 13,
      },{
        name: "Banana",
        id: 14,
      },{
        name: "Watermelon",
        id: 15,
      },{
        name: "Kiwi fruit",
        id: 16,
      }]`

And I also removed subKey='children'

Is there other props i have to change?

**Comment by duymnguyen9** [comment]
found the solution :)

**Comment by ashik112** [comment]
> found the solution :)

what was the solution?

**Comment by ashik112** [comment]
anyway, found it too

```
<SectionedMultiSelect
....
readOnlyHeadings={false}
/>
```
