### ISSUE TITLE
Close modal by tapping the background

### ISSUE THREAD

**Issue by jaltin** [renrizzolo/react-native-sectioned-multi-select#76]
Hi,

I love this component, thanks a lot for all the hard work @renrizzolo!

I would like to be able to close the modal by tapping the greyed out background (I prefer this to showing the cancel button for closing the modal).

Is this possible to do?

**Comment by renrizzolo** [comment]
Thanks!
added in 0.6.3 - just add the `ModalWithTouchable` prop.
Let me know if any problems.

**Comment by jaltin** [comment]
Hi @renrizzolo.

Sorry for this very late reply, but I just wanted to tell you that the ModalWithTouchable prop works wonderfully!

Thanks a lot for your hard work on this project!
