### ISSUE TITLE
Ajax Support

### ISSUE THREAD

**Issue by Athuli7** [renrizzolo/react-native-sectioned-multi-select#8]
This is ones of the best packages I've seen. Is there anyway we can incorporate Ajax into it ?

**Comment by renrizzolo** [comment]
Thanks @Athuli7, do you mean for pagination so you run a function to load more results when you get to the bottom of the list?

**Comment by Athuli7** [comment]
Not exactly, but yeah. The package is good for limited data set that you have locally.
I'm looking for a select2 / selectize like option to filter(server side) through 400K entries.
Anything in the pipeline?

**Comment by enkhtulga** [comment]
When will this feature add?

**Comment by renrizzolo** [comment]
@enkhtulga I have no plans to implement this myself, but I welcome any PRs / discussion on how to go about it.
