### ISSUE TITLE
why dont show selectText='Choose some things...'  on iphone

### ISSUE THREAD

**Issue by biology-w** [renrizzolo/react-native-sectioned-multi-select#82]
why dont show selectText='Choose some things...'  on iphone:
-------------------------------------------------------------
[video](https://weibo.com/tv/v/H8Iz8i4H5?fid=1034:4320779249342234)
--------------------------------------------------code-----
import React, { Component } from 'react';
import {
  View
} from 'react-native';
import SectionedMultiSelect from 'react-native-sectioned-multi-select';

const items = [
  {
    name: "Fruits",
    id: 0,
    children: [{
      name: "Apple",
      id: 10,
    },{
      name: "Strawberry",
      id: 17,
    },{
      name: "Pineapple",
      id: 13,
    },{
      name: "Banana",
      id: 14,
    },{
      name: "Watermelon",
      id: 15,
    },{
      name: "Kiwi fruit",
      id: 16,
    }]
  },
  {
    name: "Gems",
    id: 1,
    children: [{
      name: "Quartz",
      id: 20,
    },{
      name: "Zircon",
      id: 21,
    },{
      name: "Sapphire",
      id: 22,
    },{
      name: "Topaz",
      id: 23,
    }]
  },
  {
    name: "Plants",
    id: 2,
    children: [{
      name: "Mother In Law\'s Tongue",
      id: 30,
    },{
      name: "Yucca",
      id: 31,
    },{
      name: "Monsteria",
      id: 32,
    },{
      name: "Palm",
      id: 33,
    }]
  },
]

export default class App extends Component {
  constructor(){
    super()
    this.state = {
      selectedItems: [],
    _}_
  }
  onSelectedItemsChange = (selectedItems) => {
    this.setState({ selectedItems });
  }

  render() {
    return (
      <View>

        <SectionedMultiSelect
          items={items}
          uniqueKey='id'
          subKey='children'
          selectText='Choose some things...'
          showDropDowns={true}
          readOnlyHeadings={true}
          onSelectedItemsChange={this.onSelectedItemsChange}
          selectedItems={this.state.selectedItems}
        />

      </View>
    );
  }
}

**Comment by saubcy** [comment]
just wrap SectionedMultiSelect with ScrollView like this：
`<ScrollView>
 <SectionedMultiSelect/>
</ScrollView>`
