### ISSUE TITLE
Can I open a new modal inside this library?

### ISSUE THREAD

**Issue by kirhim** [renrizzolo/react-native-sectioned-multi-select#84]
I am trying to open an additional modal when I click on the item. For example, say I click Apple, I want to open a new modal. Should I use `onConfirm`?

**Comment by renrizzolo** [comment]
`onConfirm` fires when you press the confirm button.
`onSelectedItemsChange` / `onSelectedItemObjectsChange` fire when an item is selected/deselected.
I'm not sure whether you'll be able to get a modal to show on top of the existing modal (without being inside it) though.
