### ISSUE TITLE
After selecting value with long text, it's automatically show's option sectioned label

### ISSUE THREAD

**Issue by ganesh98a** [renrizzolo/react-native-sectioned-multi-select#90]
![screenshot_20190121-231504](https://user-images.githubusercontent.com/30721102/51491058-32da8f00-1dd3-11e9-8b8e-762c305effad.png)
![screenshot_20190121-231514](https://user-images.githubusercontent.com/30721102/51491046-2e15db00-1dd3-11e9-9e2e-ab1596c616e5.png)

How do i show the seleted option text val with long text directly? Below has following code 

<SectionedMultiSelect
        hideConfirm={'true'}
        items={subContractorList}
        uniqueKey='id'
        subKey='list'
        selectText='Select'
        showDropDowns={false}
        hideSearch={true}
        single={true}
        showChips={false}
        itemNumberOfLines={1}
        selectLabelNumberOfLines={1}
        readOnlyHeadings={true}
        alwaysShowSelectText={true}
        onSelectedItemsChange={this.onSelectedSubContractorItemsChange}
        selectedItems={this.props.selectedSubContractorItems} />

**Comment by renrizzolo** [comment]
Hey, is the problem that the text is truncated? If so you need to change `itemNumberOfLines` to 2 (or more).

**Comment by ganesh98a** [comment]
Hai @renrizzolo. the option text value is end with in the line after selecting that value it's show the value directly in front. when i select the option with more than a line it's show option sectioned name. like i attached screenshot for reference above
"_Engineering Inc" sectioned label under i select "joel hadson <michealbuhrely+engineering@yopmail.com>" after in front it's show's only "_Engineering Inc" But i need to show "joel hadson <michealbuhrely+engineering@yopmail.com>"

Can you help me to solve it  ?

**Comment by ganesh98a** [comment]
@renrizzolo. Thanks for your support. i have mission the item unique id's with mapping of section id

Any way thanks it's works great....
