### ISSUE TITLE
have direct uri in iconKey

### ISSUE THREAD

**Issue by koo27** [renrizzolo/react-native-sectioned-multi-select#91]
I'm fetching the list of the items from external api, and the object is formed like following:

```
products: [
{
_id: "5c10f9e057b7f4000e0a1383",
name: "ProductOne",
image: "https://image.com/image.jpeg",
category: "CategoryOne",
updatedAt: "2019-01-27T08:37:57.479Z",
status: "In Progress"
}
]
```

That means that I get the "iconKey" from "image", but the app throws this warning `Invalid prop 'name' of value 'https://image.com/image.jpeg' supplied to 'Icon', expected one of the ["..."]`

I guess that is because in the example you use `icon: { uri: ('address') }` and I'm using direct uri.
Is there a way to solve this without manipulating my original object?

P.s.
the url "https://image.com/image.jpeg" is just a placeholder I wrote here on github.

**Comment by renrizzolo** [comment]
It's like this so it can tell the difference between an image which has to be an object like `{ uri: 'uri'}` in react native, and a string which will be used for the icon name.

As it stands you would have to massage your incoming data to comply. The only other solution would be to add a `iconType` prop or something.

**Comment by koo27** [comment]
Ok thank you for your quick reply.
I forked your awesome project and changed `ItemIcon.js`.
I also changed directly the chips render because using the customChipsRenderer prop becomes way to difficult since you have to handle the selectItem, removeItem, etc.

However it would be useful to have the choise of the icon type as prop.

Keep up the great work

**Comment by renrizzolo** [comment]
@koo27 cool, thanks!
