### ISSUE TITLE
Improvement on customChipsRenderer

### ISSUE THREAD

**Issue by Cadrach** [renrizzolo/react-native-sectioned-multi-select#95]
Hi,

First, thanks for a great library!

I am using the **customChipsRenderer** function to display the chips differently (to have an icon for them)

The problem is that the chip is supposed to have a "remove item" icon, but the method to do this is not exposed as a param to **customChipsRenderer** so it is impossible to keep the behavior.

Would be possible to add the **_removeItem** method in the parameters passed to **customChipsRenderer** ?

Thanks!

**Comment by renrizzolo** [comment]
you have to add a ref to `<SectionedMultiSelect />`
`ref={SectionedMultiSelect => this.SectionedMultiSelect = SectionedMultiSelect}`

then you can access the class methods:
`onPress={() => { this.SectionedMultiSelect._removeItem(item) }}>`

The full example:
```js
  customChipsRenderer = (props) => {
    return (
      <View>
        {props.selectedItems.map((singleSelectedItem) => {
          const item = this.SectionedMultiSelect._findItem(singleSelectedItem)

          if (!item || !item[props.displayKey]) return null

          return (
            <View key={item[props.uniqueKey]}>
              <TouchableOpacity onPress={() => { this.SectionedMultiSelect._removeItem(item) }}>
                  <Text>{item[props.displayKey]}</Text>
              </TouchableOpacity>
            </View>
            )
        })} 
      </View>
    )
  }
```
