### ISSUE TITLE
How to apply styling on the input?

### ISSUE THREAD

**Issue by hasnainalimj** [renrizzolo/react-native-sectioned-multi-select#98]
the default height is too much so i just want to change the height of this input and also want to apply border on this.
![Screenshot_20190329-164959](https://user-images.githubusercontent.com/40880679/55233457-88f00680-524a-11e9-8882-4107a8643d8e.png)
![Screenshot_20190329-165214](https://user-images.githubusercontent.com/40880679/55233458-89889d00-524a-11e9-8b73-c6d2ee7a876a.png)

**Comment by renrizzolo** [comment]
The select toggle is what you need to style.
add this to your styles object:
```
        selectToggle: {
              borderWidth: 1,
              borderRadius: 8,
              borderColor: 'silver',
              paddingHorizontal: 16,
              paddingVertical: 8,
            },
```

I'm not seeing any problems with the height / layout, but you could add a fixed height to that too.

**Comment by navedkhan012** [comment]
> selectToggle

not working on my case
