### ISSUE TITLE
Hide Selected Items or apply custom jsx to items

### ISSUE THREAD

**Issue by ismailkhan89** [renrizzolo/react-native-sectioned-multi-select#99]
I want to have my custom style for selected items.
and i want to hide current selected items 
I removed this line  selectedItems={this.state.selectedItems} but didn't worked for me.

if some has done it kindly share your code ..
Thanks in advance

**Comment by renrizzolo** [comment]
Hi, you can try to use the styles to hide them. Both `item and `selectedItem` are available on the styles object.
I haven't tested it but you could try this:
```
styles={{
item: {  } // your custom style
 selectedItem: { transform: [{ scale: 0 }] }
}}

(unless you're talking about hiding the chips, in which case you can use the `showChips` prop).
